tunnel: fd7c785e-3ed2-441f-947a-5f8f62281963
credentials-file: C:\Users\youse\.cloudflared\fd7c785e-3ed2-441f-947a-5f8f62281963.json
protocol: http2

ingress:
  - hostname: api.envizion.work
    service: http://localhost:3000
  - hostname: envizion.work
    path: /Loma
    service: http://localhost:8080
  - service: http_status:404
