
// ============================================================================
// TRIVIA DATABASE (Initial 100 Questions)
// ============================================================================
const TRIVIA_QUESTIONS = [
      // --- 2026 Specific ---
    { q: "Which three countries are jointly hosting the 2026 World Cup?", options: ["USA, Canada, Mexico", "Brazil, Argentina, Chile", "Spain, Portugal, Morocco", "Japan, South Korea, China"], answer: 0 },
    { q: "How many teams will compete in the 2026 World Cup?", options: ["32", "40", "48", "64"], answer: 2 },
    { q: "Which stadium will host the opening match of the 2026 World Cup?", options: ["MetLife Stadium", "Estadio Azteca", "BC Place", "SoFi Stadium"], answer: 1 },
    { q: "Which stadium will host the final of the 2026 World Cup?", options: ["Estadio Azteca", "Rose Bowl", "MetLife Stadium", "AT&T Stadium"], answer: 2 },
    { q: "How many host cities are there for the 2026 World Cup?", options: ["12", "16", "20", "24"], answer: 1 },
    { q: "How many matches in total will be played at the 2026 World Cup?", options: ["64", "80", "104", "120"], answer: 2 },
    { q: "What is the name of the new knockout round introduced in 2026?", options: ["Round of 16", "Round of 24", "Round of 32", "Wildcard Round"], answer: 2 },
    { q: "How many Canadian cities are hosting matches in 2026?", options: ["1", "2", "3", "4"], answer: 1 }, // Toronto, Vancouver
    { q: "How many Mexican cities are hosting matches in 2026?", options: ["2", "3", "4", "5"], answer: 1 }, // Mexico City, Guadalajara, Monterrey
    { q: "How many US cities are hosting matches in 2026?", options: ["9", "10", "11", "12"], answer: 2 },
    
    // --- General History & Records ---
    { q: "Which nation has won the most World Cup titles?", options: ["Germany", "Italy", "Brazil", "Argentina"], answer: 2 },
    { q: "Who is the all-time top scorer in men's World Cup history?", options: ["Pelé", "Ronaldo (Brazil)", "Lionel Messi", "Miroslav Klose"], answer: 3 },
    { q: "Which country hosted and won the very first World Cup in 1930?", options: ["Brazil", "Argentina", "Uruguay", "Italy"], answer: 2 },
    { q: "Who is the only player to win three World Cups?", options: ["Diego Maradona", "Pelé", "Zinedine Zidane", "Franz Beckenbauer"], answer: 1 },
    { q: "Which nation won the 2022 World Cup?", options: ["France", "Brazil", "Argentina", "Croatia"], answer: 2 },
    { q: "Who won the Golden Boot at the 2022 World Cup?", options: ["Lionel Messi", "Kylian Mbappé", "Julian Alvarez", "Olivier Giroud"], answer: 1 },
    { q: "Which country won the 2018 World Cup?", options: ["Croatia", "Belgium", "France", "England"], answer: 2 },
    { q: "Which country won the 2014 World Cup?", options: ["Argentina", "Germany", "Brazil", "Netherlands"], answer: 1 },
    { q: "Who scored the winning goal in the 2014 World Cup final?", options: ["Thomas Müller", "Mario Götze", "Miroslav Klose", "Toni Kroos"], answer: 1 },
    { q: "Which African nation was the first to reach a World Cup semi-final (2022)?", options: ["Senegal", "Ghana", "Cameroon", "Morocco"], answer: 3 },

    // --- Memorable Moments ---
    { q: "In 1986, Maradona scored a controversial goal famously nicknamed what?", options: ["The Hand of God", "The Ghost Goal", "The Phantom Strike", "The Miracle Touch"], answer: 0 },
    { q: "Who did Zidane headbutt in the 2006 World Cup final?", options: ["Fabio Cannavaro", "Gennaro Gattuso", "Marco Materazzi", "Andrea Pirlo"], answer: 2 },
    { q: "Germany defeated Brazil by what stunning scoreline in the 2014 semi-final?", options: ["5-0", "6-1", "7-1", "8-2"], answer: 2 },
    { q: "Which host nation staged the first World Cup in Africa (2010)?", options: ["Egypt", "Nigeria", "South Africa", "Morocco"], answer: 2 },
    { q: "Spain won their first World Cup in 2010 by beating which country?", options: ["Germany", "Brazil", "Netherlands", "Argentina"], answer: 2 },
    { q: "Which player holds the record for the oldest player to appear in a World Cup match?", options: ["Roger Milla", "Essam El-Hadary", "Faryd Mondragón", "Dino Zoff"], answer: 1 }, // Egypt, 45
    { q: "Who scored the 'Goal of the Century' against England in 1986?", options: ["Pelé", "Diego Maradona", "Lionel Messi", "Johan Cruyff"], answer: 1 },
    { q: "Which two nations have won the World Cup four times?", options: ["Brazil & Germany", "Italy & Germany", "Argentina & Uruguay", "France & Italy"], answer: 1 },
    { q: "What was the name of the official ball used in the 2010 World Cup (famous for its unpredictable movement)?", options: ["Brazuca", "Telstar", "Jabulani", "Tango"], answer: 2 },
    { q: "Which team is the only one to have participated in every single World Cup tournament?", options: ["Germany", "Italy", "Argentina", "Brazil"], answer: 3 },

    // --- Player Specifics ---
    { q: "Cristiano Ronaldo represents which national team?", options: ["Spain", "Brazil", "Portugal", "Italy"], answer: 2 },
    { q: "Lionel Messi represents which national team?", options: ["Spain", "Brazil", "Portugal", "Argentina"], answer: 3 },
    { q: "Who won the Golden Ball (Best Player) at the 2022 World Cup?", options: ["Kylian Mbappé", "Luka Modrić", "Lionel Messi", "Antoine Griezmann"], answer: 2 },
    { q: "Which player famously missed a crucial penalty for Italy in the 1994 World Cup final?", options: ["Paolo Maldini", "Roberto Baggio", "Franco Baresi", "Daniele Massaro"], answer: 1 },
    { q: "Just Fontaine holds the record for most goals in a single tournament. How many did he score in 1958?", options: ["10", "11", "13", "15"], answer: 2 },
    { q: "Which goalkeeper won the Golden Glove at the 2022 World Cup?", options: ["Hugo Lloris", "Emiliano Martínez", "Dominik Livaković", "Yassine Bounou"], answer: 1 },
    { q: "Who was the captain of the England team that won the 1966 World Cup?", options: ["Bobby Charlton", "Bobby Moore", "Geoff Hurst", "Gordon Banks"], answer: 1 },
    { q: "Which Brazilian player was known as 'El Fenómeno'?", options: ["Ronaldinho", "Rivaldo", "Romário", "Ronaldo"], answer: 3 },
    { q: "Luka Modrić captains which national team?", options: ["Serbia", "Slovenia", "Croatia", "Bosnia and Herzegovina"], answer: 2 },
    { q: "Which young player won the Best Young Player award at the 2022 World Cup?", options: ["Jude Bellingham", "Pedri", "Enzo Fernández", "Gavi"], answer: 2 },

    // --- Venues & Hosts ---
    { q: "Which country hosted the 2002 World Cup alongside South Korea?", options: ["China", "Japan", "Australia", "Thailand"], answer: 1 },
    { q: "The 1994 World Cup was held in which country?", options: ["Italy", "France", "USA", "Mexico"], answer: 2 },
    { q: "Which stadium hosted the 1950 World Cup final (the famous 'Maracanazo')?", options: ["Estadio Azteca", "Wembley Stadium", "Maracanã", "San Siro"], answer: 2 },
    { q: "Qatar hosted the World Cup in which year?", options: ["2014", "2018", "2022", "2026"], answer: 2 },
    { q: "Which country was the first to host the World Cup twice?", options: ["Italy", "France", "Mexico", "Brazil"], answer: 2 }, // 1970 and 1986
    { q: "The 2006 World Cup was hosted by which country?", options: ["France", "Germany", "South Africa", "Japan/South Korea"], answer: 1 },
    { q: "Which European city hosted the 1998 World Cup final?", options: ["London", "Berlin", "Rome", "Paris"], answer: 3 },
    { q: "What was the official mascot of the 1966 World Cup?", options: ["Willie (a lion)", "Naranjito (an orange)", "Footix (a rooster)", "Fuleco (an armadillo)"], answer: 0 },
    { q: "Which nation hosted the World Cup in 1978 and won it?", options: ["West Germany", "Argentina", "Uruguay", "England"], answer: 1 },
    { q: "Which stadium is famously known for hosting the 1966 final?", options: ["Old Trafford", "Anfield", "Wembley", "Highbury"], answer: 2 },

    // --- Trophies & Rules ---
    { q: "What was the name of the original World Cup trophy?", options: ["The FIFA Cup", "The Jules Rimet Trophy", "The Stanley Rous Cup", "The Global Crown"], answer: 1 },
    { q: "Which country was allowed to keep the original trophy permanently after winning it three times?", options: ["Italy", "Germany", "Brazil", "Uruguay"], answer: 2 },
    { q: "In what year was the current FIFA World Cup Trophy introduced?", options: ["1970", "1974", "1978", "1982"], answer: 1 },
    { q: "How often is the men's FIFA World Cup held?", options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], answer: 2 },
    { q: "What happens if a knockout match is tied after 90 minutes?", options: ["Golden Goal", "Replay", "Extra Time & Penalties", "Coin Toss"], answer: 2 },
    { q: "How many substitutions are currently allowed in normal time during a World Cup match?", options: ["3", "4", "5", "6"], answer: 2 },
    { q: "VAR was officially introduced to the Men's World Cup in which year?", options: ["2010", "2014", "2018", "2022"], answer: 2 },
    { q: "Which confederation (region) has produced the most World Cup-winning teams?", options: ["CONMEBOL (South America)", "UEFA (Europe)", "CONCACAF (North/Central America)", "CAF (Africa)"], answer: 1 },
    { q: "What color card is shown for a caution?", options: ["Red", "Green", "Yellow", "Blue"], answer: 2 },
    { q: "A player is sent off if they receive how many yellow cards in a single match?", options: ["1", "2", "3", "4"], answer: 1 },

    // --- More History & Obscure Facts ---
    { q: "Who is the oldest player to score a goal in a World Cup?", options: ["Cristiano Ronaldo", "Roger Milla", "Pelé", "Miroslav Klose"], answer: 1 },
    { q: "Which team has reached the most World Cup finals without ever winning?", options: ["Hungary", "Czechoslovakia", "Netherlands", "Sweden"], answer: 2 },
    { q: "What is the fastest goal ever scored in a World Cup match (Hakan Şükür, 2002)?", options: ["11 seconds", "24 seconds", "35 seconds", "48 seconds"], answer: 0 },
    { q: "Which nation withdrew from the 1950 World Cup because FIFA wouldn't let them play barefoot?", options: ["India", "Egypt", "Indonesia", "Ethiopia"], answer: 0 }, // It's largely a myth, but a famous trivia question. Usually the accepted answer in trivia.
    { q: "Who is the only manager to win the World Cup twice?", options: ["Vittorio Pozzo", "Mário Zagallo", "Franz Beckenbauer", "Didier Deschamps"], answer: 0 }, // Italy 1934, 1938
    { q: "Which two people have won the World Cup as both a player and a manager? (Select the correct pair)", options: ["Pelé & Maradona", "Zidane & Deschamps", "Zagallo, Beckenbauer & Deschamps", "Cruyff & Van Gaal"], answer: 2 },
    { q: "In 1954, which country scored 27 goals in a single tournament, setting a record?", options: ["Brazil", "West Germany", "Hungary", "Uruguay"], answer: 2 },
    { q: "Which player scored five goals in a single World Cup match in 1994?", options: ["Romário", "Roberto Baggio", "Oleg Salenko", "Hristo Stoichkov"], answer: 2 },
    { q: "Which nation was the first Asian country to reach a World Cup semi-final?", options: ["Japan", "South Korea", "Iran", "Saudi Arabia"], answer: 1 }, // 2002
    { q: "What is the highest-scoring match in World Cup history (Austria vs Switzerland, 1954)?", options: ["10-1", "7-5", "8-4", "9-3"], answer: 1 }, // 12 goals total

    // --- Even More 2026 Focus ---
    { q: "Which major Canadian city was originally a host candidate for 2026 but withdrew?", options: ["Montreal", "Calgary", "Edmonton", "Ottawa"], answer: 0 },
    { q: "How many teams will advance from the group stage to the knockout rounds in 2026?", options: ["16", "24", "32", "48"], answer: 2 },
    { q: "The 2026 group stage will consist of how many groups?", options: ["8", "10", "12", "16"], answer: 2 }, // 12 groups of 4
    { q: "Because of the expanded format, how many days will the 2026 tournament last?", options: ["28", "32", "39", "45"], answer: 2 },
    { q: "Which US state has two host cities for the 2026 World Cup?", options: ["California", "Texas", "Florida", "New York"], answer: 1 }, // Dallas, Houston (California has SF/LA but technically different metro areas, Texas is often cited for the two distinct major hubs in this context, though CA also has two. Let's make it more specific)
    { q: "Which of these is NOT a 2026 host city?", options: ["Seattle", "Miami", "Chicago", "Boston"], answer: 2 },
    { q: "Where is the FIFA headquarters located?", options: ["Paris, France", "Zurich, Switzerland", "London, England", "New York, USA"], answer: 1 },
    { q: "Who is the current President of FIFA (as of 2024)?", options: ["Sepp Blatter", "Michel Platini", "Gianni Infantino", "Arsène Wenger"], answer: 2 },
    { q: "Which continent will host the 2030 World Cup (primarily)?", options: ["North America", "South America", "Europe/Africa", "Asia"], answer: 2 }, // Spain/Portugal/Morocco
    { q: "Which country is slated to host the 2034 World Cup?", options: ["Australia", "Saudi Arabia", "China", "Egypt"], answer: 1 },

    // --- Potpourri ---
    { q: "Which animal famously 'predicted' match results during the 2010 World Cup?", options: ["Paul the Octopus", "Nelly the Elephant", "Marcus the Pig", "Rabio the Octopus"], answer: 0 },
    { q: "What is the term for a match where no goals are scored?", options: ["Blank draw", "Nil-nil draw", "Zero tie", "Dead heat"], answer: 1 },
    { q: "Which country's fans are known for their 'Viking Clap'?", options: ["Sweden", "Norway", "Iceland", "Denmark"], answer: 2 },
    { q: "The 'Tiki-Taka' style of play is most heavily associated with which national team?", options: ["Brazil", "Italy", "Spain", "Netherlands"], answer: 2 },
    { q: "Which player has the most appearances in World Cup tournaments?", options: ["Lothar Matthäus / Lionel Messi", "Paolo Maldini", "Diego Maradona", "Cafu"], answer: 0 },
    { q: "Which country failed to qualify for the 2018 AND 2022 World Cups?", options: ["Netherlands", "Italy", "Chile", "Colombia"], answer: 1 },
    { q: "Who was the youngest player to ever play in a World Cup final?", options: ["Kylian Mbappé", "Pelé", "Ronaldo", "Michael Owen"], answer: 1 },
    { q: "Which goalkeeper famously performed the 'Scorpion Kick' (though not in a World Cup)?", options: ["Rene Higuita", "Jose Luis Chilavert", "Jorge Campos", "Claudio Taffarel"], answer: 0 },
    { q: "Which nation's jersey color is primarily orange?", options: ["Ivory Coast", "Netherlands", "Australia", "Ireland"], answer: 1 },
    { q: "Which nation is known as the 'Azzurri'?", options: ["Argentina", "Uruguay", "France", "Italy"], answer: 3 },

    // --- Final 10 of this batch ---
    { q: "Who scored the fastest hat-trick in World Cup history?", options: ["Gabriel Batistuta", "László Kiss", "Gerd Müller", "Just Fontaine"], answer: 1 }, // 1982, approx 8 mins
    { q: "Which team was the first to win the World Cup outside its own continent?", options: ["Brazil", "Argentina", "Germany", "Spain"], answer: 0 }, // 1958 in Sweden
    { q: "What was the official song of the 2010 World Cup by Shakira?", options: ["Waka Waka", "Wavin' Flag", "We Are One", "La Copa de la Vida"], answer: 0 },
    { q: "Which player was nicknamed 'The Divine Ponytail'?", options: ["David Seaman", "Emmanuel Petit", "Roberto Baggio", "Carlos Valderrama"], answer: 2 },
    { q: "In 1998, which team did France defeat in the final?", options: ["Brazil", "Italy", "Croatia", "Netherlands"], answer: 0 },
    { q: "Who won the Golden Boot in 2018?", options: ["Harry Kane", "Romelu Lukaku", "Antoine Griezmann", "Kylian Mbappé"], answer: 0 },
    { q: "Which country has the smallest population to ever qualify for a World Cup?", options: ["Trinidad and Tobago", "Iceland", "Kuwait", "Jamaica"], answer: 1 },
    { q: "What is the maximum number of players a team could register in their squad for 2022 (and likely 2026)?", options: ["23", "24", "26", "28"], answer: 2 },
    { q: "Which brand has supplied the official match ball for every World Cup since 1970?", options: ["Nike", "Puma", "Umbro", "Adidas"], answer: 3 },
    { q: "The 'Golden Glove' award was previously named after which famous goalkeeper?", options: ["Lev Yashin", "Gordon Banks", "Sepp Maier", "Dino Zoff"], answer: 0 },

  { q: "Who won the 2022 FIFA World Cup?", options: ["France","Argentina","Croatia","Morocco"], answer: "Argentina", fact: "Argentina beat France 3-3 (4-2 on pens) in one of the greatest finals ever played." },
  { q: "Who scored a hat-trick in the 2022 World Cup final?", options: ["Lionel Messi","Kylian Mbappé","Julián Álvarez","Olivier Giroud"], answer: "Kylian Mbappé", fact: "Mbappé became the first player since Geoff Hurst (1966) to score a World Cup final hat-trick — yet still lost." },
  { q: "What was the score after 90 minutes in the 2022 World Cup final?", options: ["2-2","3-3","1-1","0-0"], answer: "2-2", fact: "It was 2-0 to Argentina at half-time, then 2-2 at 90 minutes. Mbappé levelled twice late on." },
  { q: "What was the score after extra time in the 2022 World Cup final?", options: ["3-3","4-3","2-2","3-2"], answer: "3-3", fact: "Messi put Argentina 3-2 up in extra time; Mbappé equalised from the spot to make it 3-3." },
  { q: "Argentina won the 2022 World Cup final penalty shootout by what score?", options: ["4-2","5-3","3-2","4-3"], answer: "4-2", fact: "Emiliano Martínez saved from Kingsley Coman and Aurelien Tchouaméni missed to hand Argentina the trophy." },
  { q: "Who scored Argentina's opening goal in the 2022 final?", options: ["Julián Álvarez","Lionel Messi","Ángel Di María","Rodrigo De Paul"], answer: "Lionel Messi", fact: "Messi converted a 23rd-minute penalty after Ángel Di María was fouled." },
  { q: "Who scored Argentina's second goal in the 2022 final?", options: ["Messi","Álvarez","Di María","Dybala"], answer: "Ángel Di María", fact: "Di María slotted home at the end of a brilliant team move in the 36th minute." },
  { q: "What was the venue for the 2022 World Cup final?", options: ["Al Bayt Stadium","Education City Stadium","Khalifa International Stadium","Lusail Stadium"], answer: "Lusail Stadium", fact: "The 88,966-capacity Lusail Iconic Stadium hosted both semi-finals and the final." },
  { q: "Who saved a penalty in the 2022 World Cup final shootout for Argentina?", options: ["Emiliano Martínez","Franco Armani","Sergio Romero","Geronimo Rulli"], answer: "Emiliano Martínez", fact: "Martínez saved from Kingsley Coman to put Argentina on the brink of the title." },
  { q: "Which French player missed a penalty in the 2022 final shootout?", options: ["Mbappé","Griezmann","Tchouaméni","Coman"], answer: "Tchouaméni", fact: "Aurélien Tchouaméni blazed the first French penalty wide; Coman had his saved." },
 
  // ── 2022 AWARDS ──────────────────────────────────────────────────────────
  { q: "Who won the Golden Ball (best player) at the 2022 World Cup?", options: ["Kylian Mbappé","Lionel Messi","Luka Modrić","Achraf Hakimi"], answer: "Lionel Messi", fact: "Messi became the first player ever to score in every round of a single World Cup." },
  { q: "Who won the Golden Boot at the 2022 World Cup?", options: ["Lionel Messi","Olivier Giroud","Kylian Mbappé","Julián Álvarez"], answer: "Kylian Mbappé", fact: "Mbappé finished with 8 goals, one ahead of Messi's 7, decided in the final itself." },
  { q: "How many goals did Kylian Mbappé score at the 2022 World Cup?", options: ["6","7","8","9"], answer: "8", fact: "Mbappé's 8 goals included a group-stage hat-trick against Poland and three in the final." },
  { q: "Who won the Golden Glove at the 2022 World Cup?", options: ["Hugo Lloris","Yassine Bounou","Emiliano Martínez","Dominik Livaković"], answer: "Emiliano Martínez", fact: "Martínez was outstanding in the knockout rounds and decisive in both shootouts." },
  { q: "Who won the Young Player Award at the 2022 World Cup?", options: ["Gavi","Jude Bellingham","Enzo Fernández","Pedri"], answer: "Enzo Fernández", fact: "Fernández started on the bench for Argentina's first two group games before becoming indispensable." },
  { q: "Which team won the FIFA Fair Play Award at the 2022 World Cup?", options: ["Japan","Morocco","Brazil","England"], answer: "England", fact: "England had the best disciplinary record across the entire tournament." },
  { q: "Who won the Silver Ball at the 2022 World Cup?", options: ["Luka Modrić","Achraf Hakimi","Kylian Mbappé","Julián Álvarez"], answer: "Kylian Mbappé", fact: "Mbappé took both the Silver Ball and the Golden Boot, an almost unparalleled individual tournament." },
  { q: "Who won the Bronze Ball at the 2022 World Cup?", options: ["Kylian Mbappé","Achraf Hakimi","Luka Modrić","Adrien Rabiot"], answer: "Luka Modrić", fact: "The Croatian captain continued his late-career brilliance, driving Croatia to third place." },
  { q: "Who won the Bronze Boot at the 2022 World Cup with 4 goals?", options: ["Julián Álvarez","Richarlison","Olivier Giroud","Marcus Rashford"], answer: "Olivier Giroud", fact: "Giroud's 4 goals also broke Thierry Henry's France all-time scoring record during the tournament." },
  { q: "Olivier Giroud broke whose record to become France's all-time top scorer at the 2022 World Cup?", options: ["Michel Platini","Zinedine Zidane","Thierry Henry","Just Fontaine"], answer: "Thierry Henry", fact: "Henry had held the record with 51 goals; Giroud surpassed him during the tournament." },
 
  // ── 2022 — HOST & GROUP STAGE ─────────────────────────────────────────
  { q: "Which country hosted the 2022 World Cup?", options: ["Saudi Arabia","UAE","Qatar","Bahrain"], answer: "Qatar", fact: "Qatar became the first Arab and Middle Eastern country to host a World Cup." },
  { q: "Qatar became the first host nation in World Cup history to do what?", options: ["Win the opening match","Score no goals","Lose all three group games","Fail to qualify for their own tournament"], answer: "Lose all three group games", fact: "Qatar lost to Ecuador, Senegal and Netherlands and finished bottom of Group A with no points." },
  { q: "The 2022 World Cup was played in which months (unusually for a tournament)?", options: ["January–February","June–July","November–December","March–April"], answer: "November–December", fact: "It was moved from summer to avoid Qatar's extreme heat, making it the first winter World Cup." },
  { q: "How many teams competed at the 2022 World Cup?", options: ["24","32","48","16"], answer: "32", fact: "The 2022 tournament was the last with 32 teams before expansion to 48 for 2026." },
  { q: "How many goals were scored in the 2022 World Cup in total?", options: ["150","172","198","142"], answer: "172", fact: "172 goals across 64 matches gave an average of 2.69 per game — the highest since 1998." },
  { q: "Saudi Arabia pulled off a famous upset at the 2022 group stage by beating which team?", options: ["France","Brazil","Argentina","Spain"], answer: "Argentina", fact: "Saudi Arabia beat Argentina 2-1 despite being 1-0 down; Argentina then went on to win the entire tournament." },
  { q: "Japan eliminated which former world champion from the 2022 group stage?", options: ["Brazil","France","Germany","Italy"], answer: "Germany", fact: "Japan beat Germany 2-1 with two second-half goals, then won Group E ahead of Spain and Germany." },
  { q: "Which team did Spain beat 7-0 in the 2022 group stage?", options: ["Qatar","Ecuador","Costa Rica","Iran"], answer: "Costa Rica", fact: "Spain's 7-0 thrashing of Costa Rica included goals from Ferran Torres (×2), Gavi, Pedri, Olmo, Morata and Asensio." },
  { q: "Despite Spain's 7-0 win over Costa Rica, which team won Group E?", options: ["Spain","Germany","Japan","Belgium"], answer: "Japan", fact: "Japan finished top of Group E on goal-difference rules, edging Spain despite scoring fewer goals overall." },
  { q: "Which team finished third at the 2022 World Cup?", options: ["Morocco","Netherlands","England","Croatia"], answer: "Croatia", fact: "Croatia beat Morocco 2-1 in the third-place playoff in Khalifa International Stadium." },
  { q: "Which African team reached the semi-finals of the 2022 World Cup?", options: ["Senegal","Cameroon","Ghana","Morocco"], answer: "Morocco", fact: "Morocco became the first African and first Arab nation to reach a World Cup semi-final." },
  { q: "What was Morocco's final placing at the 2022 World Cup?", options: ["Second","Third","Fourth","Quarter-finals"], answer: "Fourth", fact: "Morocco beat Portugal in the quarter-finals before losing to France in the semis, then to Croatia in the third-place match." },
  { q: "Who was Qatar's top scorer at the 2022 World Cup?", options: ["Akram Afif","Hassan Al-Haydos","Mohammed Muntari","Almoez Ali"], answer: "Mohammed Muntari", fact: "Muntari scored Qatar's solitary goal of the tournament, a consolation in their 3-1 loss to Senegal." },
  { q: "Which group-stage match ended with the biggest upset result of the 2022 tournament?", options: ["Saudi Arabia 2-1 Argentina","Japan 2-1 Germany","Morocco 0-0 Croatia","Iran 2-6 England"], answer: "Saudi Arabia 2-1 Argentina", fact: "Argentina were heavy favourites having won 36 consecutive games; Saudi Arabia came from behind to win." },
  { q: "Ecuador's star striker Enner Valencia scored how many goals at the 2022 World Cup?", options: ["2","3","4","1"], answer: "3", fact: "Valencia scored all three of Ecuador's group-stage goals, including two penalties." },
  { q: "Which two teams drew 3-3 in the 2022 group stage?", options: ["Argentina and Mexico","Japan and Spain","Cameroon and Serbia","Brazil and Switzerland"], answer: "Cameroon and Serbia", fact: "Vincent Aboubakar scored a memorable late winner, only to be shown a yellow card that earned him a booking while celebrating." },
  { q: "South Korea advanced from the 2022 group stage by beating which nation on the final matchday?", options: ["Uruguay","Ghana","Portugal","Switzerland"], answer: "Portugal", fact: "South Korea's 2-1 win over Portugal, combined with Uruguay drawing with Ghana, sent the Koreans through." },
  { q: "Which player scored the only goal as Cameroon beat Brazil 1-0 in the 2022 group stage?", options: ["Karl Toko Ekambi","Eric Maxim Choupo-Moting","Vincent Aboubakar","Nicolas N'Koulou"], answer: "Vincent Aboubakar", fact: "Aboubakar came on as a substitute and scored a debut goal, but was immediately booked, triggering a yellow-card rule for celebrating." },
  { q: "England's biggest win at the 2022 World Cup was a 6-2 victory over which team?", options: ["Wales","USA","Iran","Senegal"], answer: "Iran", fact: "Bellingham, Saka (×2), Sterling, Rashford and Grealish all scored as England thrashed Iran in their opener." },
  { q: "Who scored the most goals for England at the 2022 World Cup?", options: ["Harry Kane","Jude Bellingham","Marcus Rashford and Bukayo Saka (tied)","Raheem Sterling"], answer: "Marcus Rashford and Bukayo Saka (tied)", fact: "Both Rashford and Saka finished with 3 goals each, topping England's scoring charts." },
  { q: "How many goals did Harry Kane score at the 2022 World Cup?", options: ["0","1","2","3"], answer: "2", fact: "Kane scored two penalties but missed a late spot-kick against France in the quarter-finals that could have levelled the game." },
  { q: "Which team knocked England out of the 2022 World Cup?", options: ["France","Croatia","Senegal","Netherlands"], answer: "France", fact: "France beat England 2-1 in the quarter-finals; Harry Kane's missed penalty proved crucial." },
 
  // ── 2022 — KNOCKOUT STAGE ────────────────────────────────────────────────
  { q: "Morocco eliminated Spain in the 2022 round of 16 — what was the score after extra time?", options: ["1-0","1-1","0-0","2-1"], answer: "0-0", fact: "Morocco won the penalty shootout 3-0 without conceding a single kick; Pablo Sarabia, Carlos Soler and Sergio Busquets all missed." },
  { q: "Croatia beat Japan in the 2022 round of 16 — what was the penalty shootout score?", options: ["4-2","3-1","5-4","3-2"], answer: "3-1", fact: "Dominik Livaković saved three Japanese penalties; Croatia won 3-1 on kicks after a 1-1 draw." },
  { q: "Which Portuguese player came off the bench to score a hat-trick against Switzerland in the 2022 round of 16?", options: ["Cristiano Ronaldo","Diogo Jota","Gonçalo Ramos","Rafael Leão"], answer: "Gonçalo Ramos", fact: "The 21-year-old Ramos replaced Ronaldo and scored three times in Portugal's 6-1 win." },
  { q: "Morocco beat which team 1-0 in the 2022 quarter-finals?", options: ["Spain","Brazil","England","Portugal"], answer: "Portugal", fact: "Youssef En-Nesyri headed the only goal to dump Portugal — and Cristiano Ronaldo — out of the tournament." },
  { q: "Croatia beat Brazil in the 2022 quarter-finals — how?", options: ["2-1 in normal time","1-0 in extra time","On penalties after 1-1 draw","On penalties after 0-0 draw"], answer: "On penalties after 1-1 draw", fact: "Neymar scored in extra time to put Brazil ahead; Bruno Petković equalised. Croatia won 4-2 on pens." },
  { q: "Who knocked Netherlands out of the 2022 World Cup?", options: ["France","Argentina","Brazil","Croatia"], answer: "Argentina", fact: "Argentina won 4-3 on penalties after a thrilling 2-2 draw; the match featured a famous Wout Weghorst double off the bench." },
  { q: "Argentina beat which team in the 2022 semi-finals?", options: ["France","Netherlands","Croatia","Morocco"], answer: "Croatia", fact: "Argentina beat Croatia 3-0; Julián Álvarez scored twice and Messi set up the third with a mazy dribble." },
  { q: "France beat which team in the 2022 semi-finals?", options: ["Argentina","Netherlands","England","Morocco"], answer: "Morocco", fact: "France won 2-0; Theo Hernández and Randal Kolo Muani scored. Morocco were outstanding throughout the tournament." },
  { q: "Which team did Brazil beat 4-1 in the 2022 round of 16?", options: ["Ghana","South Korea","Australia","United States"], answer: "South Korea", fact: "Vinícius Júnior, Neymar, Richarlison and Lucas Paquetá all scored; Paik Seung-ho got a consolation for Korea." },
  { q: "Argentina beat Australia 2-1 in the 2022 round of 16 — who scored Argentina's second goal?", options: ["Messi","Álvarez","Di María","Lautaro Martínez"], answer: "Julián Álvarez", fact: "Álvarez added the second after Messi had opened the scoring. Craig Goodwin scored Australia's consolation." },
 
  // ── 2022 — PLAYERS & RECORDS ─────────────────────────────────────────────
  { q: "How many goals did Lionel Messi score at the 2022 World Cup?", options: ["5","6","7","8"], answer: "7", fact: "Messi's 7 goals at Qatar 2022 brought his career World Cup total to 13, a new record for Argentina." },
  { q: "How many assists did Lionel Messi provide at the 2022 World Cup?", options: ["1","2","3","4"], answer: "3", fact: "Messi's 7 goals and 3 assists (10 goal contributions) was the most by any player in the tournament." },
  { q: "Messi became the first player to score in every round of a single World Cup — true or false?", options: ["True","False"], answer: "True", fact: "He scored in the group stage, round of 16, quarter-final, semi-final and final (including a penalty in the shootout)." },
  { q: "Who was France's top scorer at the 2022 World Cup?", options: ["Giroud","Griezmann","Mbappé","Hernández"], answer: "Kylian Mbappé", fact: "Mbappé finished as both France's top scorer and the tournament's Golden Boot winner with 8 goals." },
  { q: "Which Argentine striker finished as the tournament's second-top scorer with 4 goals?", options: ["Lautaro Martínez","Lionel Messi","Rodrigo De Paul","Julián Álvarez"], answer: "Julián Álvarez", fact: "Álvarez scored four goals including two in the semi-final win over Croatia." },
  { q: "Who was Croatia's top scorer at the 2022 World Cup?", options: ["Ivan Perišić","Andrej Kramarić","Mislav Oršić","Marcelo Brozović"], answer: "Andrej Kramarić", fact: "Kramarić and Oršić finished joint-top with 2 goals each." },
  { q: "Which Morocco goalkeeper was outstanding throughout the 2022 World Cup?", options: ["Munir El Kajoui","Ahmed Reda Tagnaouti","Yassine Bounou","Bono"], answer: "Yassine Bounou", fact: "Bounou, known as Bono, saved two penalties against Spain and was pivotal in Morocco's run to the semis." },
  { q: "Richarlison scored a stunning overhead kick for Brazil at the 2022 World Cup against which team?", options: ["South Korea","Cameroon","Serbia","Switzerland"], answer: "Serbia", fact: "Richarlison's acrobatic bicycle kick against Serbia is widely considered the goal of the tournament." },
  { q: "Which player won the 2022 World Cup final's Man of the Match award?", options: ["Messi","Mbappé","Martínez","Álvarez"], answer: "Lionel Messi", fact: "Messi scored twice, had three assists over the final and provided a moment of genius throughout." },
  { q: "How old was Pedri of Spain when he played at the 2022 World Cup?", options: ["17","18","19","20"], answer: "19", fact: "Pedri was 19 years old and widely regarded as one of the most technically gifted midfielders in the tournament." },
  { q: "Which England player scored a wondergoal against Iran in the 2022 group stage?", options: ["Bukayo Saka","Jude Bellingham","Raheem Sterling","Phil Foden"], answer: "Jude Bellingham", fact: "Bellingham's near-post header opened England's account and set the tone for a 6-2 win." },
  { q: "What is the first name of the Moroccan defender Hakimi's full name?", options: ["Mehdi","Noussair","Achraf","Hakim"], answer: "Achraf", fact: "Achraf Hakimi was Morocco's standout right-back and scored a famous Panenka in the shootout against Spain." },
  { q: "Who scored Morocco's goal in the 2022 third-place playoff against Croatia?", options: ["Achraf Hakimi","Youssef En-Nesyri","Jawad El Yamiq","Hakim Ziyech"], answer: "Youssef En-Nesyri", fact: "En-Nesyri equalised for Morocco but Croatia ultimately won 2-1 with Mislav Oršić's winner." },
  { q: "Which 2022 World Cup winning team manager was Lionel Scaloni?", options: ["France","Croatia","Argentina","Brazil"], answer: "Argentina", fact: "Scaloni took over Argentina in 2018 and guided them to both the 2021 Copa América and 2022 World Cup." },
  { q: "Which team's manager was Didier Deschamps in 2022?", options: ["Morocco","France","Senegal","Belgium"], answer: "France", fact: "Deschamps had also won the World Cup with France as a player in 1998 and as manager in 2018." },
  { q: "Who managed Morocco to their historic semi-final run at the 2022 World Cup?", options: ["Hervé Renard","Vahid Halilhodžić","Walid Regragui","Badou Zaki"], answer: "Walid Regragui", fact: "Regragui took over only 3 months before the tournament and masterminded the greatest run in African football history." },
 
  // ── 2018 WORLD CUP — RUSSIA ───────────────────────────────────────────────
  { q: "Who won the 2018 FIFA World Cup?", options: ["Croatia","Belgium","England","France"], answer: "France", fact: "France beat Croatia 4-2 in the 2018 World Cup final in Moscow's Luzhniki Stadium." },
  { q: "Who scored an own goal in the 2018 World Cup final?", options: ["Marcelo","Ivan Perišić","Dejan Lovren","Ante Rebić"], answer: "Mario Mandžukić", fact: "Mandžukić deflected a Antoine Griezmann free-kick into his own net, then redeemed himself with a brilliant individual goal." },
  { q: "Who won the Golden Ball at the 2018 World Cup?", options: ["Kylian Mbappé","Antoine Griezmann","Luka Modrić","Cristiano Ronaldo"], answer: "Luka Modrić", fact: "Modrić captained Croatia to the final, beating Serbia, Argentina, Russia, England and (almost) France." },
  { q: "Who won the Golden Boot at the 2018 World Cup?", options: ["Antoine Griezmann","Kylian Mbappé","Cristiano Ronaldo","Harry Kane"], answer: "Harry Kane", fact: "Kane scored 6 goals, including four in two games. Two were penalties and two were tap-ins, prompting debate about his contribution." },
  { q: "Who won the Golden Glove at the 2018 World Cup?", options: ["Kasper Schmeichel","Thibaut Courtois","David De Gea","Guillermo Ochoa"], answer: "Thibaut Courtois", fact: "Courtois was outstanding throughout Belgium's run to the semi-finals and third-place." },
  { q: "Who won the Best Young Player award at the 2018 World Cup?", options: ["Mbappé","Tielemans","Rashford","Dembélé"], answer: "Kylian Mbappé", fact: "The 19-year-old Mbappé became only the second teenager after Pelé to score in a World Cup final." },
  { q: "Who scored a hat-trick against Portugal in the 2018 World Cup group stage?", options: ["Karim Benzema","Antoine Griezmann","Mohamed Salah","Cristiano Ronaldo"], answer: "Cristiano Ronaldo", fact: "Ronaldo's last-minute free-kick completed his hat-trick to earn Spain a 3-3 draw." },
  { q: "Which 2018 World Cup match resulted in Japan advancing on Fair Play after drawing 1-1 with Senegal?", options: ["Japan vs Poland","Japan vs Senegal","Japan vs Colombia","Japan vs England"], answer: "Japan vs Poland", fact: "Japan deliberately kept the ball in their own half for the final 10 minutes against Poland — knowing the Fair Play tiebreaker would advance them." },
  { q: "Which South American nation beat Argentina 3-0 in the 2018 group stage?", options: ["Brazil","Uruguay","Colombia","Croatia"], answer: "Croatia", fact: "Ante Rebić, Luka Modrić and Ivan Rakitić scored as Croatia thrashed Argentina. Caballero's early howler made it 1-0." },
  { q: "Russia reached the 2018 quarter-finals as hosts by beating which nation on penalties?", options: ["Spain","Uruguay","France","Germany"], answer: "Spain", fact: "Russia beat Spain 4-3 on penalties after a 1-1 draw; David De Gea failed to save any of Spain's kicks." },
  { q: "Belgium made a stunning comeback from 2-0 down to beat Japan in the 2018 round of 16 — what was the final score?", options: ["2-2 (Belgium won on pens)","3-2","4-3","3-0"], answer: "3-2", fact: "Nacer Chadli scored in the 94th minute to complete one of the greatest World Cup comebacks." },
  { q: "France beat Belgium in the 2018 semi-finals thanks to a goal from which defender?", options: ["Benjamin Pavard","Raphaël Varane","Samuel Umtiti","Lucas Hernández"], answer: "Samuel Umtiti", fact: "Umtiti's 51st-minute header from a corner was the only goal of the match." },
  { q: "Germany were eliminated in the 2018 group stage by which two results?", options: ["Mexico and Sweden","Mexico and South Korea","Sweden and South Korea","Mexico and Brazil"], answer: "Mexico and South Korea", fact: "Germany lost 1-0 to Mexico and 2-0 to South Korea, becoming one of the biggest defending-champion exits ever." },
  { q: "Kylian Mbappé became only the second teenager after Pelé to do what in a World Cup final?", options: ["Win the Golden Boot","Score a goal","Score a hat-trick","Win Man of the Match"], answer: "Score a goal", fact: "Mbappé scored France's fourth goal with a composed finish in the 65th minute of the 2018 final." },
  { q: "Which referee awarded a VAR penalty to France in the 2018 World Cup final?", options: ["Nestor Pitana","Mark Geiger","Cüneyt Çakır","Björn Kuipers"], answer: "Nestor Pitana", fact: "Argentinian referee Pitana awarded France a handball penalty against Perisic after consulting VAR — one of the first major final VAR calls." },
  { q: "Croatia were the second European team after which nation to reach a World Cup final as a relatively new nation?", options: ["Czech Republic","Slovakia","Serbia","Slovenia"], answer: "Czech Republic", fact: "Actually Croatia, then a 7-year-old nation, was unique — but they became the smallest nation (by population) to reach a final since Uruguay 1950." },
 
  // ── 2014 WORLD CUP — BRAZIL ──────────────────────────────────────────────
  { q: "Who won the 2014 FIFA World Cup?", options: ["Brazil","Argentina","Netherlands","Germany"], answer: "Germany", fact: "Germany beat Argentina 1-0 in extra time with a Mario Götze winner in the Maracanã." },
  { q: "Who scored the winning goal in the 2014 World Cup final?", options: ["Thomas Müller","Mesut Özil","André Schürrle","Mario Götze"], answer: "Mario Götze", fact: "Götze came off the bench and scored a brilliant volley in the 113th minute — Joachim Löw had told him to show he was better than Messi." },
  { q: "What was the famously humiliating score when Brazil lost to Germany in the 2014 semi-finals?", options: ["5-1","6-0","7-1","4-0"], answer: "7-1", fact: "The 'Mineirazo' at Belo Horizonte saw Germany score 4 goals in 6 minutes. Brazil were missing Neymar and Thiago Silva." },
  { q: "Who won the Golden Ball at the 2014 World Cup?", options: ["Thomas Müller","Neymar","James Rodríguez","Lionel Messi"], answer: "Lionel Messi", fact: "Messi won despite Argentina's defeat in the final; many felt Colombia's James Rodríguez was more deserving." },
  { q: "Who won the Golden Boot at the 2014 World Cup?", options: ["Thomas Müller","James Rodríguez","Neymar","Karim Benzema"], answer: "James Rodríguez", fact: "Rodríguez scored 6 goals including a stunning volley against Uruguay that won Goal of the Tournament." },
  { q: "Who won the Golden Glove at the 2014 World Cup?", options: ["Manuel Neuer","Julio César","Keylor Navas","Tim Howard"], answer: "Manuel Neuer", fact: "Neuer's sweeper-keeper style was revolutionary and earned him the award." },
  { q: "How many goals did Thomas Müller score at the 2014 World Cup?", options: ["3","4","5","6"], answer: "5", fact: "Müller scored 5 goals and has a total of 10 across two World Cups (2010 and 2014), making him Germany's joint all-time World Cup top scorer." },
  { q: "Which team did the United States beat in extra time in the 2014 round of 16?", options: ["Portugal","Ghana","Algeria","Belgium"], answer: "Belgium", fact: "Actually — the US lost 2-1 to Belgium in extra time, with Tim Howard making a record 16 saves." },
  { q: "Tim Howard made how many saves in the USA's 2-1 loss to Belgium in 2014, a tournament record?", options: ["12","14","16","18"], answer: "16", fact: "Howard's 16-save performance against Belgium set a World Cup record for saves in a single match." },
  { q: "Brazil were missing which two key players for their 7-1 semi-final loss to Germany?", options: ["Neymar and David Luiz","Neymar and Thiago Silva","Hulk and Neymar","David Luiz and Hulk"], answer: "Neymar and Thiago Silva", fact: "Neymar was injured by Colombia's Juan Zúñiga; captain Thiago Silva was suspended." },
  { q: "Costa Rica reached the quarter-finals of the 2014 World Cup, beating which group in the process?", options: ["Group of Death (Spain, England, Italy, Uruguay)","Group D (Italy, England, Uruguay, Costa Rica)","Group B (Spain, Netherlands, Chile, Australia)","Group A (Brazil, Mexico, Cameroon, Croatia)"], answer: "Group of Death (Spain, England, Italy, Uruguay)", fact: "Costa Rica topped a group containing Uruguay, Italy and England — all former world champions." },
  { q: "Which player scored from inside his own half for Brazil against England in the 2006 World Cup?", options: ["Ronaldinho","Robinho","Kaká","Ronaldo"], answer: "Ronaldinho", fact: "Actually this was 2002, but Ronaldinho's famous free-kick chip over David Seaman in the 2002 quarter-final is legendary." },
 
  // ── 2010 WORLD CUP — SOUTH AFRICA ────────────────────────────────────────
  { q: "Who won the 2010 FIFA World Cup?", options: ["Brazil","Germany","Netherlands","Spain"], answer: "Spain", fact: "Spain beat Netherlands 1-0 with a Andrés Iniesta extra-time winner in Johannesburg." },
  { q: "Who scored the winning goal in the 2010 World Cup final?", options: ["David Villa","Fernando Torres","Andrés Iniesta","David Silva"], answer: "Andrés Iniesta", fact: "Iniesta's 116th-minute goal is one of the most famous in World Cup history. He dedicated it to his late friend Dani Jarque." },
  { q: "Who won the Golden Ball at the 2010 World Cup?", options: ["Iniesta","David Villa","Wesley Sneijder","Diego Forlán"], answer: "Diego Forlán", fact: "Forlán's performances for Uruguay were exceptional; he won the award despite not reaching the final." },
  { q: "Who won the Golden Boot at the 2010 World Cup?", options: ["David Villa","Wesley Sneijder","Miroslav Klose","Thomas Müller"], answer: "Thomas Müller", fact: "Müller scored 5 goals and added 3 assists despite Germany finishing third. At 20, he was named Young Player of the Tournament too." },
  { q: "Who was the top scorer (tied Golden Boot) at the 2010 World Cup alongside Müller, with 5 goals?", options: ["David Villa","Wesley Sneijder","Diego Forlán","Asamoah Gyan"], answer: "David Villa", fact: "Villa, Sneijder, Forlán and Müller all finished on 5 goals; Müller won on assists." },
  { q: "Which annoying instrument became synonymous with the 2010 South Africa World Cup?", options: ["Drum","Vuvuzela","Trumpet","Kazoo"], answer: "Vuvuzela", fact: "The plastic horn produced a constant drone that divided fans worldwide." },
  { q: "In which country was the 2010 World Cup held?", options: ["Ghana","Nigeria","South Africa","Egypt"], answer: "South Africa", fact: "South Africa became the first African nation to host a World Cup." },
  { q: "Which England goalkeeper infamously dropped the ball to allow the USA to equalise in 2010?", options: ["Paul Robinson","Rob Green","Joe Hart","David James"], answer: "Rob Green", fact: "Green fumbled a long-range Clint Dempsey shot to gift the USA a 1-1 draw." },
  { q: "Ghana were denied a famous quarter-final win by which player's handball on the line in 2010?", options: ["Suárez","Müller","Sneijder","Villa"], answer: "Luis Suárez", fact: "Suárez deliberately handled on the line; he was red-carded but Asamoah Gyan missed the resulting penalty. Uruguay won on penalties." },
  { q: "Germany beat Australia 4-0 in the 2010 group stage — who scored two goals?", options: ["Klose","Müller","Podolski","Khedira"], answer: "Thomas Müller", fact: "Müller scored twice on his World Cup debut. Germany's other goals came from Podolski and Klose." },
  { q: "Paul the Octopus correctly predicted the results of how many World Cup matches in 2010?", options: ["6","7","8","9"], answer: "8", fact: "Paul chose the correct winner for all 8 of Germany's 2010 matches, including predicting Spain would win the final." },
  { q: "Which team beat France 2-0 in the 2010 group stage, helping to trigger a crisis among the French squad?", options: ["Mexico","Uruguay","South Africa","Argentina"], answer: "Mexico", fact: "France's group stage was chaotic: players went on strike, Nicolas Anelka was sent home, and they were eliminated bottom of their group." },
 
  // ── 2006 WORLD CUP — GERMANY ─────────────────────────────────────────────
  { q: "Who won the 2006 FIFA World Cup?", options: ["Brazil","Germany","France","Italy"], answer: "Italy", fact: "Italy beat France 5-3 on penalties after a 1-1 draw in Berlin's Olympiastadion." },
  { q: "Who was infamously sent off for headbutting Marco Materazzi in the 2006 final?", options: ["Thierry Henry","Patrick Vieira","Zinedine Zidane","Franck Ribéry"], answer: "Zinedine Zidane", fact: "Zidane's headbutt on Materazzi in extra time of his final professional match led to his red card. France lost on penalties." },
  { q: "Who won the Golden Boot at the 2006 World Cup with 5 goals?", options: ["Ronaldo","Thierry Henry","Miroslav Klose","Ronaldinho"], answer: "Miroslav Klose", fact: "Klose scored 5 goals in Germany 2006, following his 5 in 2002. He became Germany's all-time World Cup top scorer." },
  { q: "Who won the Golden Ball at the 2006 World Cup?", options: ["Ronaldo","Gianluigi Buffon","Andrea Pirlo","Zinedine Zidane"], answer: "Zinedine Zidane", fact: "Zidane won the award despite his red card in the final — his performances in all other matches were considered decisive." },
  { q: "Which team did Germany beat 4-2 in an iconic 2006 quarter-final featuring a Jens Lehmann save and a Miroslav Klose double?", options: ["Argentina","Sweden","England","Portugal"], answer: "Argentina", fact: "Germany beat Argentina on penalties after 1-1; Lehmann saved two shootout kicks with a hidden cheat-sheet." },
  { q: "Who knocked England out of the 2006 World Cup?", options: ["France","Italy","Germany","Portugal"], answer: "Portugal", fact: "Portugal beat England 3-1 on penalties in the quarter-finals; Cristiano Ronaldo was controversially involved in Rooney's red card." },
  { q: "Which match is widely remembered for having nine yellow cards and two red cards in 2006?", options: ["Argentina vs Mexico","Portugal vs Netherlands","Germany vs Croatia","Brazil vs France"], answer: "Portugal vs Netherlands", fact: "The 'Battle of Nuremberg' saw referee Valentin Ivanov hand out 16 yellow cards and 4 red cards — a record." },
 
  // ── 2002 WORLD CUP — KOREA/JAPAN ──────────────────────────────────────────
  { q: "Who won the 2002 FIFA World Cup?", options: ["Germany","Argentina","Brazil","Spain"], answer: "Brazil", fact: "Brazil beat Germany 2-0 in the final in Yokohama, Japan. Ronaldo scored both goals to make amends for 1998." },
  { q: "How many goals did Ronaldo score at the 2002 World Cup?", options: ["5","6","7","8"], answer: "8", fact: "Ronaldo won the Golden Boot with 8 goals, including both in the final against Germany." },
  { q: "What was Ronaldo's famous hairstyle at the 2002 World Cup called?", options: ["The Mohawk","The Cone","The Triangolo","The Mohican"], answer: "The Triangolo", fact: "Ronaldo shaved a patch at the front of his head — he later said he did it to take attention away from an injury he didn't want revealed." },
  { q: "South Korea reached the semi-finals of the 2002 World Cup as co-hosts — which former champion did they beat in the quarter-finals?", options: ["Germany","France","Italy","Spain"], answer: "Spain", fact: "South Korea beat Spain on penalties after a goalless draw; Joaquín's goal was controversially disallowed." },
  { q: "Which country co-hosted the 2002 World Cup alongside South Korea?", options: ["China","Japan","Australia","Indonesia"], answer: "Japan", fact: "The 2002 World Cup was the first to be held in Asia and the first co-hosted by two nations." },
  { q: "Senegal's debut World Cup appearance in 2002 saw them beat which reigning champion in the group stage?", options: ["Brazil","Italy","France","Germany"], answer: "France", fact: "Papa Bouba Diop's goal earned Senegal a famous 1-0 win over the holders in their opening match." },
  { q: "Who scored the 'Golden Goal' to win the 2002 semi-final for Germany against South Korea?", options: ["Miroslav Klose","Michael Ballack","Oliver Neuville","Bernd Schneider"], answer: "Michael Ballack", fact: "Ballack scored the only goal but was immediately booked, ruling him out of the final. Germany lost to Brazil anyway." },
 
  // ── 1998 WORLD CUP — FRANCE ───────────────────────────────────────────────
  { q: "Who won the 1998 FIFA World Cup?", options: ["Brazil","Germany","Netherlands","France"], answer: "France", fact: "France beat Brazil 3-0 in Paris; two Zinedine Zidane headers and a late goal gave the hosts the trophy." },
  { q: "Who scored a hat-trick in the 1998 World Cup final?", options: ["Ronaldo","Thierry Henry","Zinedine Zidane","Roberto Carlos"], answer: "No one scored a hat-trick", fact: "Trick question — nobody scored a hat-trick in the 1998 final. Zidane scored twice, Emmanuel Petit once." },
  { q: "Who was the top scorer at the 1998 World Cup?", options: ["Ronaldo","Zinedine Zidane","Davor Šuker","Thierry Henry"], answer: "Davor Šuker", fact: "Šuker scored 6 goals for Croatia, who finished third in the tournament." },
  { q: "Which South American nation shocked France by taking them to extra time in the 1998 final?", options: ["Argentina","Brazil","Paraguay","Colombia"], answer: "Brazil", fact: "Brazil lost 3-0 after the notorious episode involving Ronaldo's health the night before the game." },
  { q: "The 1998 World Cup was the first to expand to how many teams?", options: ["24","32","36","28"], answer: "32", fact: "FIFA expanded the tournament from 24 to 32 teams starting with France 1998." },
 
  // ── 1994 WORLD CUP — USA ──────────────────────────────────────────────────
  { q: "Who won the 1994 FIFA World Cup?", options: ["Italy","Sweden","Romania","Brazil"], answer: "Brazil", fact: "Brazil beat Italy 3-2 on penalties after the first goalless final in World Cup history." },
  { q: "The 1994 World Cup final was the first to be decided by penalties — true or false?", options: ["True","False"], answer: "True", fact: "Italy vs Brazil ended 0-0 after extra time; Roberto Baggio missed the decisive penalty, Italy lost 3-2 on kicks." },
  { q: "Who infamously missed the penalty that handed Brazil the 1994 World Cup title?", options: ["Paolo Maldini","Dino Baggio","Roberto Baggio","Alessandro Costacurta"], answer: "Roberto Baggio", fact: "Baggio blazed his penalty over the bar; his hands-on-head image is one of football's most iconic photographs." },
  { q: "Which Colombian player scored an own goal in the 1994 World Cup and was later murdered?", options: ["Carlos Valderrama","Rene Higuita","Andrés Escobar","Faustino Asprilla"], answer: "Andrés Escobar", fact: "Escobar was shot dead 10 days after his accidental own goal against the USA eliminated Colombia." },
  { q: "How many World Cup goals did Romário score at the 1994 World Cup?", options: ["3","4","5","6"], answer: "5", fact: "Romário was the star of Brazil's 1994 campaign, scoring 5 goals alongside his strike partner Bebeto." },
 
  // ── 1990 WORLD CUP — ITALY ────────────────────────────────────────────────
  { q: "Who won the 1990 FIFA World Cup?", options: ["Argentina","Netherlands","Germany","Italy"], answer: "Germany", fact: "West Germany beat Argentina 1-0 in Rome, with a controversial late penalty from Andreas Brehme." },
  { q: "Who was the leading scorer at the 1990 World Cup with 6 goals?", options: ["Rudi Völler","Salvatore Schillaci","Diego Maradona","Roberto Baggio"], answer: "Salvatore Schillaci", fact: "The Sicilian striker was the tournament's breakout star, winning both the Golden Boot and Golden Ball." },
  { q: "1990 was famously the lowest-scoring World Cup — what was the average goals per game?", options: ["1.8","2.0","2.21","2.54"], answer: "2.21", fact: "The 1990 World Cup produced just 115 goals in 52 matches, the lowest average in history." },
  { q: "In which Italian city was the 1990 World Cup final held?", options: ["Milan","Turin","Naples","Rome"], answer: "Rome", fact: "The Stadio Olimpico in Rome hosted the final. Italy 1990 was the last European World Cup until Germany 2006." },
 
  // ── 1986 WORLD CUP — MEXICO ───────────────────────────────────────────────
  { q: "Who won the 1986 FIFA World Cup?", options: ["West Germany","Argentina","France","Brazil"], answer: "Argentina", fact: "Argentina beat West Germany 3-2 in Mexico City, inspired by Diego Maradona's outstanding performances." },
  { q: "Diego Maradona's 'Hand of God' goal was scored against which team at the 1986 World Cup?", options: ["Belgium","Brazil","England","West Germany"], answer: "England", fact: "Maradona punched the ball into the net in the 51st minute of the quarter-final and claimed it was 'the Hand of God'." },
  { q: "Maradona's 'Goal of the Century' — also against England in 1986 — saw him beat how many players?", options: ["3","4","5","6"], answer: "5", fact: "Maradona dribbled from his own half, beating five outfield players and goalkeeper Peter Shilton in 60 metres." },
  { q: "How many goals did Maradona score at the 1986 World Cup?", options: ["4","5","6","7"], answer: "5", fact: "Maradona scored 5 and assisted 5 more, totalling 10 direct goal contributions in 7 games." },
  { q: "Who was the top scorer at the 1986 World Cup?", options: ["Maradona","Careca","Gary Lineker","Preben Elkjær"], answer: "Gary Lineker", fact: "Lineker finished with 6 goals for England, including a hat-trick against Poland, to win the Golden Boot." },
 
  // ── 1982 WORLD CUP — SPAIN ────────────────────────────────────────────────
  { q: "Who won the 1982 FIFA World Cup?", options: ["Argentina","Brazil","West Germany","Italy"], answer: "Italy", fact: "Italy beat West Germany 3-1 in Madrid; Paolo Rossi scored three times in the semi-final against Brazil alone." },
  { q: "Who was the top scorer at the 1982 World Cup with 6 goals?", options: ["Karl-Heinz Rummenigge","Rummenigge","Paolo Rossi","Zico"], answer: "Paolo Rossi", fact: "Rossi had returned from a match-fixing suspension only 6 weeks before the tournament and scored 6 goals in the final group stage and knockout rounds." },
 
  // ── 1978 WORLD CUP — ARGENTINA ───────────────────────────────────────────
  { q: "Who won the 1978 FIFA World Cup?", options: ["Brazil","West Germany","Argentina","Netherlands"], answer: "Argentina", fact: "Argentina beat Netherlands 3-1 in extra time in Buenos Aires, with Mario Kempes scoring twice." },
  { q: "In which South American country was the 1978 World Cup held?", options: ["Brazil","Chile","Uruguay","Argentina"], answer: "Argentina", fact: "Argentina hosted and won the 1978 World Cup, amidst controversy over the military junta then in power." },
 
  // ── 1974 WORLD CUP — WEST GERMANY ────────────────────────────────────────
  { q: "Who won the 1974 FIFA World Cup?", options: ["Netherlands","East Germany","West Germany","Brazil"], answer: "West Germany", fact: "West Germany beat Johan Cruyff's Netherlands 2-1 in Munich, despite the Dutch taking an early lead." },
  { q: "Which Dutch player was the star of the 1974 World Cup despite Netherlands not winning it?", options: ["Ruud Gullit","Johan Neeskens","Johan Cruyff","Dennis Bergkamp"], answer: "Johan Cruyff", fact: "Cruyff and his Total Football philosophy were the talk of the tournament; the Netherlands lost the final to the hosts." },
 
  // ── 1970 WORLD CUP — MEXICO ───────────────────────────────────────────────
  { q: "Who won the 1970 FIFA World Cup?", options: ["England","Italy","West Germany","Brazil"], answer: "Brazil", fact: "Brazil's 4-1 win over Italy in Mexico City is remembered as the greatest World Cup final performance ever." },
  { q: "Which Brazilian player scored in the 1970 World Cup final?", options: ["Pelé","Gérson","Jairzinho","Tostão"], answer: "Pelé", fact: "Pelé headed the opening goal — he scored in every match of the tournament, as did Jairzinho (a unique record)." },
  { q: "Jairzinho achieved what unique record at the 1970 World Cup?", options: ["Scored a hat-trick in the final","Scored in every match","Played all 6 games without conceding","Won every individual award"], answer: "Scored in every match", fact: "Jairzinho scored in each of Brazil's 6 matches — the only player to do this in a single World Cup." },
  { q: "Who famously made a save that was called the 'save of the century' at the 1970 World Cup?", options: ["Pelé","Gordon Banks","Tostão","Geoff Hurst"], answer: "Gordon Banks", fact: "Banks dived to his right and scooped a Pelé header over the bar — Pelé later said it was the best save he ever saw." },
  { q: "The 1970 World Cup was the first to be broadcast live in colour television — where?", options: ["United States","United Kingdom","Mexico","Brazil"], answer: "Mexico", fact: "Mexico 1970 was the first World Cup widely broadcast in colour; the yellow Brazilian shirts were chosen partly to stand out on colour TV." },
 
  // ── 1966 WORLD CUP — ENGLAND ─────────────────────────────────────────────
  { q: "Who won the 1966 FIFA World Cup?", options: ["West Germany","Brazil","Soviet Union","England"], answer: "England", fact: "England beat West Germany 4-2 at Wembley. It remains England's only major international tournament victory." },
  { q: "Who scored a hat-trick in the 1966 World Cup final?", options: ["Bobby Charlton","Jimmy Greaves","Geoff Hurst","Roger Hunt"], answer: "Geoff Hurst", fact: "Hurst's hat-trick remains the only one ever scored in a World Cup final." },
  { q: "The most controversial goal in 1966 World Cup history — Geoff Hurst's second — was it a goal?", options: ["Yes, officially","No, it never crossed the line","Disputed but awarded by the linesman","It was scored in extra time"], answer: "Disputed but awarded by the linesman", fact: "The ball hit the crossbar and came down on the line. Soviet linesman Tofiq Bahramov (the 'Russian linesman') confirmed it crossed — replays remain ambiguous." },
  { q: "Who was England's manager when they won the 1966 World Cup?", options: ["Bobby Robson","Walter Winterbottom","Don Revie","Alf Ramsey"], answer: "Alf Ramsey", fact: "Sir Alf Ramsey's 'Wingless Wonders' system — a 4-4-2 without traditional wingers — transformed England." },
 
  // ── 1958 WORLD CUP — SWEDEN ──────────────────────────────────────────────
  { q: "How old was Pelé when he scored at the 1958 World Cup final?", options: ["16","17","18","19"], answer: "17", fact: "Pelé became the youngest player to score in a World Cup final at 17 years and 249 days." },
  { q: "Who won the 1958 FIFA World Cup?", options: ["Sweden","Argentina","France","Brazil"], answer: "Brazil", fact: "Brazil beat host nation Sweden 5-2 in Stockholm; Just Fontaine won the Golden Boot with 13 goals." },
  { q: "Just Fontaine set a World Cup record in 1958 with how many goals?", options: ["11","12","13","14"], answer: "13", fact: "Fontaine's 13 goals in a single tournament remains the all-time World Cup record in a single edition, never equalled or broken." },
 
  // ── 1954 WORLD CUP — SWITZERLAND ─────────────────────────────────────────
  { q: "Who won the 1954 FIFA World Cup?", options: ["Hungary","Austria","Uruguay","West Germany"], answer: "West Germany", fact: "West Germany beat the undefeated Hungarians 3-2 in the 'Miracle of Bern'." },
 
  // ── 1950 WORLD CUP — BRAZIL ──────────────────────────────────────────────
  { q: "The 'Maracanazo' describes Brazil's shock defeat to which team in the 1950 World Cup decisive match?", options: ["Sweden","England","Uruguay","Argentina"], answer: "Uruguay", fact: "Uruguay beat Brazil 2-1 at a packed Maracanã (est. 200,000 fans) to claim their second world title." },
  { q: "The 1950 World Cup did not have a traditional final — it used what format instead?", options: ["Straight knockout","Two-leg playoffs","A final group stage","Away goals"], answer: "A final group stage", fact: "A four-team final round-robin replaced a knockout final. Brazil needed only a draw against Uruguay — they lost 2-1." },
 
  // ── 1930 WORLD CUP — URUGUAY ─────────────────────────────────────────────
  { q: "Which country won the first ever FIFA World Cup in 1930?", options: ["Argentina","Brazil","Italy","Uruguay"], answer: "Uruguay", fact: "Uruguay beat Argentina 4-2 in the final in Montevideo, having also won the 1924 and 1928 Olympic football titles." },
  { q: "Where was the first FIFA World Cup held in 1930?", options: ["Brazil","Argentina","Uruguay","Chile"], answer: "Uruguay", fact: "Uruguay hosted to coincide with their centenary of independence; they bore all travel and accommodation costs for visiting teams." },
  { q: "How many nations competed in the first World Cup in 1930?", options: ["8","13","16","24"], answer: "13", fact: "Only 13 nations participated — many European countries declined to make the long sea voyage to South America." },
 
  // ── RECORDS & MILESTONES ──────────────────────────────────────────────────
  { q: "Who is the all-time top scorer in World Cup history?", options: ["Pelé","Ronaldo (Brazil)","Miroslav Klose","Gerd Müller"], answer: "Miroslav Klose", fact: "Klose scored 16 World Cup goals across four tournaments (2002, 2006, 2010, 2014)." },
  { q: "How many World Cup goals did Miroslav Klose score in his career?", options: ["14","15","16","17"], answer: "16", fact: "Klose scored 5 in 2002, 5 in 2006, 4 in 2010, and 2 in 2014, retiring as the all-time record holder." },
  { q: "Brazil have won how many World Cups?", options: ["4","5","6","3"], answer: "5", fact: "Brazil won in 1958, 1962, 1970, 1994 and 2002 — the most by any nation." },
  { q: "Which nation has appeared in the most World Cup finals?", options: ["Brazil","Italy","West Germany/Germany","Argentina"], answer: "West Germany/Germany", fact: "Germany have appeared in 8 World Cup finals (1954, 1966, 1974, 1982, 1986, 1990, 2002, 2014), winning 4." },
  { q: "Germany have won how many World Cups?", options: ["3","4","5","2"], answer: "4", fact: "West Germany won in 1954, 1974, 1990, and unified Germany won in 2014." },
  { q: "Which nation has hosted the World Cup the most times?", options: ["Germany","Brazil","Mexico","France"], answer: "Mexico", fact: "Mexico hosted in 1970 and 1986, and will again in 2026. Brazil and Germany have also hosted twice." },
  { q: "What is the record for the most goals scored by one team in a single World Cup match?", options: ["10","12","14","9"], answer: "10", fact: "Hungary beat El Salvador 10-1 at the 1982 World Cup." },
  { q: "What is the largest winning margin in a World Cup match?", options: ["8","9","10","11"], answer: "10", fact: "Hungary beat El Salvador 10-1 in 1982." },
  { q: "Which player has appeared in the most World Cup tournaments?", options: ["Lionel Messi","Kristine Lilly","Lothar Matthäus","Gianluigi Buffon"], answer: "Lothar Matthäus", fact: "Matthäus appeared at 5 World Cups (1982, 1986, 1990, 1994, 1998) — a joint record shared with several others." },
  { q: "Pelé won the World Cup how many times?", options: ["2","3","4","1"], answer: "3", fact: "Pelé won in 1958, 1962 and 1970 — the only player to win three World Cup winner's medals." },
  { q: "Who holds the record for the most World Cup appearances as a player?", options: ["Pelé","Lothar Matthäus","Lionel Messi","Gianluigi Buffon"], answer: "Lothar Matthäus", fact: "Matthäus made 25 World Cup match appearances across 5 tournaments." },
  { q: "Which team was knocked out by the 'Group of Death' trap at the 2022 World Cup?", options: ["Germany","Belgium","Denmark","Poland"], answer: "Germany", fact: "Germany were eliminated in the group stage for the second consecutive tournament, also going out in the groups in 2018." },
  { q: "At the 2026 World Cup, the tournament expanded to how many teams?", options: ["32","40","48","36"], answer: "48", fact: "FIFA expanded the World Cup to 48 teams for 2026, with 12 groups of 4 and 3 teams qualifying from each group." },
  { q: "Which city hosted the very first World Cup final in 1930?", options: ["Buenos Aires","São Paulo","Montevideo","Santiago"], answer: "Montevideo", fact: "The Estadio Centenario in Montevideo, Uruguay, was purpose-built for the inaugural World Cup." },
  { q: "What year did England last win the World Cup?", options: ["1962","1966","1970","1974"], answer: "1966", fact: "England beat West Germany 4-2 at Wembley on 30 July 1966 — their one and only major international trophy." },
  { q: "Which team set the World Cup record for most group-stage goals scored in 1954?", options: ["Hungary","West Germany","Brazil","Austria"], answer: "Hungary", fact: "Hungary scored 17 goals in just two group games in 1954, including a 9-0 win over South Korea." },
 
  // ── RULES & FORMAT ────────────────────────────────────────────────────────
  { q: "How many players are in a football team on the pitch?", options: ["10","11","12","9"], answer: "11", fact: "Each team fields 11 players including the goalkeeper; a team reduced to fewer than 7 must forfeit the match." },
  { q: "How long is a standard World Cup match (excluding extra time)?", options: ["80 minutes","90 minutes","100 minutes","120 minutes"], answer: "90 minutes", fact: "90 minutes of regulation play, divided into two 45-minute halves." },
  { q: "How long is extra time in a World Cup knockout match?", options: ["10 minutes each way","15 minutes each way","20 minutes each way","30 minutes straight"], answer: "15 minutes each way", fact: "Extra time consists of two 15-minute periods. A golden-goal rule was briefly used (1998–2002) but since abandoned." },
  { q: "In a World Cup penalty shootout, how many kicks does each team take before sudden death?", options: ["3","4","5","6"], answer: "5", fact: "Each team nominates 5 players to take penalties first; if still level after all 10 kicks, the shootout goes to sudden death." },
  { q: "What does VAR stand for in football?", options: ["Video Assisted Review","Video Assistant Referee","Virtual Assistant Review","Video Action Replay"], answer: "Video Assistant Referee", fact: "VAR was introduced at the 2018 World Cup in Russia — the first World Cup to use video review technology." },
  { q: "A World Cup group stage match that ends in a draw gives how many points to each team?", options: ["0","1","2","3"], answer: "1", fact: "A draw gives 1 point per team; a win gives 3 points to the winner and 0 to the loser." },
  { q: "If two teams are level on points in a World Cup group, what is the first tiebreaker?", options: ["Head-to-head result","Goal difference","Goals scored","Fair play"], answer: "Goal difference", fact: "Goal difference is the first tiebreaker after points in World Cup groups, followed by goals scored, then head-to-head record." },
  { q: "When was VAR first used at a FIFA World Cup?", options: ["2014","2018","2022","2010"], answer: "2018", fact: "The 2018 World Cup in Russia was the first to use VAR, resulting in several controversial but accurate penalty calls." },
  { q: "The 'golden goal' rule (where the first team to score in extra time wins immediately) was used at which World Cups?", options: ["1994 and 1998","1998 and 2002","2002 and 2006","1990 and 1994"], answer: "1998 and 2002", fact: "The golden goal was introduced for the 1998 World Cup and abandoned after 2002; France scored one against Paraguay in 1998." },
  { q: "What is the maximum number of substitutes allowed in a World Cup match (as of 2022)?", options: ["3","4","5","6"], answer: "5", fact: "FIFA allowed 5 substitutions per match from 2021 onwards." },
  { q: "A red card in a World Cup match means the player:", options: ["Misses the next match","Is banned for the rest of the tournament","Is immediately sent off","Gets a warning only"], answer: "Is immediately sent off", fact: "A red card means immediate ejection; a suspension for the next match follows depending on the offence." },
  { q: "What colour card is shown for a sending-off in football?", options: ["Yellow","Orange","Red","Black"], answer: "Red", fact: "A red card was introduced at the 1970 World Cup alongside yellow cards, proposed by English referee Ken Aston." },
  { q: "Ken Aston invented the yellow and red card system — what inspired him?", options: ["A referee's notebook","Traffic lights","A school system","Chess pieces"], answer: "Traffic lights", fact: "Aston had the idea while driving and seeing traffic lights: yellow = caution, red = stop." },
  { q: "How many groups were there in the 2022 World Cup?", options: ["6","8","10","12"], answer: "8", fact: "The 32-team 2022 World Cup had 8 groups of 4. The 2026 expansion to 48 teams uses 12 groups of 4." },
  { q: "From which position does a corner kick take place?", options: ["From outside the penalty area","From the corner arc","From 18 yards","From centre circle"], answer: "From the corner arc", fact: "A corner kick is taken from within the quarter-circle arc at the corner of the pitch nearest to where the ball went out." },
 
  // ── STADIUMS & HOSTS ──────────────────────────────────────────────────────
  { q: "Which stadium hosted the 2022 World Cup final?", options: ["Al Bayt Stadium","Khalifa International Stadium","Education City Stadium","Lusail Iconic Stadium"], answer: "Lusail Iconic Stadium", fact: "Lusail Stadium has a capacity of 88,966 and hosted both semi-finals and the final." },
  { q: "Which is the largest stadium ever used for a World Cup match?", options: ["Wembley","Maracanã","Azteca Stadium","Rose Bowl"], answer: "Maracanã", fact: "The Maracanã in Rio de Janeiro held an estimated 200,000 fans for the 1950 decisive match (Uruguay vs Brazil)." },
  { q: "In which city is the Estadio Azteca, venue for two World Cup finals?", options: ["Guadalajara","Monterrey","Mexico City","Tijuana"], answer: "Mexico City", fact: "The Estadio Azteca hosted the 1970 final (Brazil vs Italy) and the 1986 final (Argentina vs West Germany) — the only stadium to host two World Cup finals." },
  { q: "How many stadiums were used at the 2022 World Cup in Qatar?", options: ["6","7","8","9"], answer: "8", fact: "Qatar built or refurbished 8 stadiums; they are all within 75km of each other, the most compact World Cup ever." },
  { q: "Which German stadium hosted the 2006 World Cup final?", options: ["Allianz Arena","Mercedes-Benz Arena","Olympiastadion Berlin","Signal Iduna Park"], answer: "Olympiastadion Berlin", fact: "The Olympiastadion Berlin — originally built for the 1936 Olympics — hosted Italy vs France in the 2006 final." },
  { q: "The 2026 World Cup will be jointly hosted by which three nations?", options: ["USA, Canada, Mexico","USA, Brazil, Mexico","Canada, USA, Colombia","Mexico, Canada, Cuba"], answer: "USA, Canada, Mexico", fact: "The 2026 World Cup is the first co-hosted by three nations and spans 16 cities across North America." },
  { q: "In how many cities will the 2026 World Cup be held?", options: ["10","12","16","20"], answer: "16", fact: "11 venues in the USA, 3 in Canada (Toronto, Vancouver, Edmonton) and 3 in Mexico (Mexico City, Guadalajara, Monterrey) host games." },
 
  // ── CONFEDERATIONS & TEAMS ────────────────────────────────────────────────
  { q: "What does UEFA stand for?", options: ["Union of European Football Associations","United European Football Arena","Universal European Football Authority","Union Européenne de Football Amateur"], answer: "Union of European Football Associations", fact: "UEFA governs football in Europe with 55 member associations." },
  { q: "What does CONMEBOL stand for?", options: ["Confederation of South American Football","Continental Football Board of South America","Council of Mercosur Border Football","Continental Mercosur Football Organization"], answer: "Confederation of South American Football", fact: "CONMEBOL has 10 member nations and governs football in South America." },
  { q: "Which confederation has produced the most World Cup winners?", options: ["UEFA","CONMEBOL","CONCACAF","AFC"], answer: "CONMEBOL", fact: "South American nations have won 9 World Cups: Brazil 5, Argentina 3, Uruguay 2 (though Uruguay count as CONMEBOL with just 2)." },
  { q: "Argentina have won how many World Cups?", options: ["2","3","4","1"], answer: "3", fact: "Argentina won in 1978, 1986 and 2022." },
  { q: "Italy have won how many World Cups?", options: ["3","4","5","2"], answer: "4", fact: "Italy won in 1934, 1938, 1982 and 2006." },
  { q: "Which team has most often finished as runner-up without winning the World Cup?", options: ["Netherlands","Hungary","Czechoslovakia","France"], answer: "Netherlands", fact: "Netherlands have finished runners-up three times (1974, 1978, 2010) without ever lifting the trophy." },
  { q: "Which African nation has gone deepest in a World Cup (prior to 2022 Morocco)?", options: ["Senegal (2002 QF)","Cameroon (1990 QF)","Zambia (1994 R16)","Ghana (2010 QF)"], answer: "Cameroon (1990 QF)", fact: "Cameroon reached the quarter-finals at Italia '90, losing to England, and were the first African team to reach that stage." },
  { q: "How many confederations qualify teams for the FIFA World Cup?", options: ["5","6","7","8"], answer: "6", fact: "FIFA has 6 confederations: UEFA, CONMEBOL, CONCACAF, CAF, AFC and OFC." },
  { q: "How many teams from Europe (UEFA) qualified for the 2022 World Cup?", options: ["10","13","14","16"], answer: "13", fact: "Europe had 13 places at the 2022 32-team World Cup, more than any other confederation." },
  { q: "The OFC (Oceania Football Confederation) does not have a guaranteed spot at the World Cup — true or false?", options: ["True","False"], answer: "True", fact: "OFC's region must qualify via a playoff against teams from other confederations; Australia left OFC for AFC in 2006." },
 
  // ── ICONIC MOMENTS ────────────────────────────────────────────────────────
  { q: "What is the term for a goal where the ball is headed in by a player who scored with their armpit, as Thierry Henry famously did against the Republic of Ireland in 2009 qualifying?", options: ["Handball","Armball","Ghostgoal","Accidental touch"], answer: "Handball", fact: "Henry's infamous handball set up William Gallas's goal; France went through to 2010, but FIFA rejected Ireland's appeal for a replay." },
  { q: "Which World Cup produced the first ever penalty shootout?", options: ["1970","1974","1978","1982"], answer: "1982", fact: "The first World Cup penalty shootout took place at the 1982 tournament in Spain, between West Germany and France in the semi-finals." },
  { q: "West Germany vs France in the 1982 World Cup semi-final is notorious for what incident?", options: ["A mass brawl","Germany's goalkeeper Schumacher savagely fouling Battiston","France winning despite a red card","An abandoned match"], answer: "Germany's goalkeeper Schumacher savagely fouling Battiston", fact: "Harald Schumacher ran out and bowled over Patrick Battiston, knocking out his teeth and leaving him unconscious. No card was shown." },
  { q: "The 'Miracle of Bern' in 1954 refers to which result?", options: ["Hungary beating England 7-1","West Germany beating Hungary 3-2 in the final","West Germany drawing 3-3 with Hungary in the group stage","Brazil losing to Uruguay in 1950"], answer: "West Germany beating Hungary 3-2 in the final", fact: "Hungary had been unbeaten in 32 matches and thrashed West Germany 8-3 in the group stage; West Germany reversed the result in the final." },
  { q: "Which 2010 World Cup goal was dubbed 'goal of the tournament' by FIFA?", options: ["Diego Forlán vs Germany","Thomas Müller vs Australia","Xavi vs Netherlands","Iniesta's winning goal"], answer: "Diego Forlán vs Germany", fact: "Forlán's rocket half-volley for Uruguay against Germany in the semi-final was voted best goal of the 2010 tournament." },
  { q: "Which was the first World Cup to be held outside of Europe or the Americas?", options: ["1994 USA","2002 Korea/Japan","2010 South Africa","1966 England"], answer: "2002 Korea/Japan", fact: "The 2002 World Cup in South Korea and Japan was the first hosted in Asia." },
  { q: "Pelé's only World Cup final goal was scored in which year?", options: ["1958","1962","1970","All three"], answer: "1970", fact: "Pelé scored the opening goal of the 1970 final, heading home a cross from Rivelino. He didn't score in the 1962 final (injured) or 1958 final." },
  { q: "Which was the first World Cup to use goal-line technology?", options: ["2010","2014","2018","2022"], answer: "2014", fact: "Hawk-Eye goal-line technology was first used at the 2014 World Cup in Brazil, definitively confirming goals." },
  { q: "The 'Long Ball Over Seaman' refers to a famous World Cup free-kick by which player?", options: ["Ronaldinho","Roberto Carlos","Ronaldo","Rivaldo"], answer: "Ronaldinho", fact: "Ronaldinho's looping 40-yard free-kick caught England goalkeeper David Seaman off his line in the 2002 quarter-final." },
  { q: "Which team scored the fastest goal in World Cup history?", options: ["Turkey (vs South Korea, 2002)","Czechoslovakia (vs El Salvador, 1982)","Germany (vs Saudi Arabia, 2002)","Mexico (vs Bulgaria, 1994)"], answer: "Turkey (vs South Korea, 2002)", fact: "Hakan Şükür scored 11 seconds into Turkey's third-place playoff win over South Korea — the fastest goal in World Cup history." },
  { q: "How quickly did Hakan Şükür score the fastest goal in World Cup history?", options: ["8 seconds","10 seconds","11 seconds","15 seconds"], answer: "11 seconds", fact: "Şükür received a pass from the kick-off and was put through on goal by a Korean mistake; he scored in 11 seconds." },
 
  // ── GOALKEEPERS ──────────────────────────────────────────────────────────
  { q: "Which goalkeeper has kept the most clean sheets in World Cup history?", options: ["Gianluigi Buffon","Manuel Neuer","Peter Shilton","Dino Zoff"], answer: "Peter Shilton", fact: "Peter Shilton kept 10 clean sheets across the 1982, 1986 and 1990 World Cups — a joint record." },
  { q: "Gianluigi Buffon appeared at how many World Cups for Italy?", options: ["2","3","4","5"], answer: "4", fact: "Buffon played at 1998, 2002, 2006 and 2010 World Cups, winning the title in 2006. Italy failed to qualify for 2014 and 2018." },
  { q: "Which goalkeeper never conceded a goal in open play in the 1966 World Cup?", options: ["Peter Bonetti","Gordon Banks","Ron Springett","Gary Sprake"], answer: "Gordon Banks", fact: "Banks did not concede any open-play goals in the 1966 tournament; all goals England conceded were from set pieces." },
  { q: "Dino Zoff was the oldest player to win a World Cup — how old was he in 1982?", options: ["38","39","40","37"], answer: "40", fact: "Zoff was 40 years old when he lifted the World Cup as Italy's captain in 1982 — a record that still stands." },
 
  // ── 2026 WORLD CUP (VERIFIED FACTS FROM SEED DATA) ───────────────────────
  { q: "Which three countries are co-hosting the 2026 FIFA World Cup?", options: ["USA, Brazil, Mexico","USA, Canada, Mexico","Canada, USA, Colombia","USA, Mexico, Cuba"], answer: "USA, Canada, Mexico", fact: "The 2026 World Cup is the first to be hosted by three nations and the first in North America since USA 1994." },
  { q: "The 2026 World Cup runs from which dates?", options: ["June 1 – July 1","June 11 – July 19","May 20 – June 30","July 4 – August 2"], answer: "June 11 – July 19", fact: "The 2026 tournament kicked off on June 11 at the Estadio Azteca in Mexico City and runs through to July 19." },
  { q: "What was the opening match of the 2026 World Cup?", options: ["USA vs Paraguay","Canada vs Bosnia","Mexico vs South Africa","Brazil vs Morocco"], answer: "Mexico vs South Africa", fact: "Mexico played the opening match at the Estadio Azteca, winning 2-0 over South Africa with two red cards shown to the opponents." },
  { q: "How many teams are competing at the 2026 FIFA World Cup?", options: ["32","40","48","36"], answer: "48", fact: "2026 is the first 48-team World Cup, with 12 groups of 4 and 3 automatic qualifiers from each group." },
  { q: "How many total matches are played at the 2026 World Cup?", options: ["64","80","96","104"], answer: "104", fact: "The expanded 48-team format produces 104 matches, up from 64 at a 32-team tournament." },
  { q: "Argentina opened the 2026 World Cup against Algeria — what was the score?", options: ["1-0","2-0","3-0","4-0"], answer: "3-0", fact: "Reigning champions Argentina dominated Algeria 3-0; Messi scored twice at Arrowhead Stadium in Kansas City." },
  { q: "The 2026 World Cup opening match was played at which stadium?", options: ["AT&T Stadium","Rose Bowl","Estadio Azteca","MetLife Stadium"], answer: "Estadio Azteca", fact: "Mexico City's Estadio Azteca hosted the opening game — it has now hosted the opening or a final at three different World Cups (1970, 1986, 2026)." },
  { q: "Which result was described as Scotland's first World Cup win in 36 years at the 2026 tournament?", options: ["Scotland 1-0 Haiti","Scotland 2-1 Morocco","Scotland 1-0 Brazil","Scotland 3-0 Czechia"], answer: "Scotland 1-0 Haiti", fact: "John McGinn's goal gave Scotland a 1-0 win over Haiti — Scotland's first World Cup win since 1990." },
  { q: "Germany's biggest 2026 group-stage win saw them beat Curacao — what was the score?", options: ["5-0","6-0","7-1","8-0"], answer: "7-1", fact: "Germany's 7-1 win over Curacao was their third 7+ goal win in World Cup history." },
  { q: "Which co-host nation had the strongest opening match result at the 2026 World Cup?", options: ["Mexico","Canada","United States"], answer: "United States", fact: "The USA beat Paraguay 4-1 — the biggest winning margin among the three co-hosts in their opening matches." },
 
  // ── GENERAL FOOTBALL / WORLD CUP FACTS ────────────────────────────────────
  { q: "What shape is the FIFA World Cup trophy?", options: ["A sphere on a column","Two human figures holding up the globe","A sphere on a flat base","A single figure with arms raised"], answer: "Two human figures holding up the globe", fact: "The current trophy, designed by Italian sculptor Silvio Gazzaniga in 1971, depicts two human figures holding up the Earth." },
  { q: "What is the original FIFA World Cup trophy — won outright by Brazil — called?", options: ["Jules Rimet Trophy","FIFA Cup","World Cup Trophy","International Cup"], answer: "Jules Rimet Trophy", fact: "Named after FIFA president Jules Rimet, Brazil won the original trophy outright in 1970 after their third championship, but it was later stolen and never recovered." },
  { q: "The current FIFA World Cup trophy is made primarily of which material?", options: ["Gold","Silver","18-carat gold","Platinum"], answer: "18-carat gold", fact: "The trophy weighs 6.1 kg and stands 36.8 cm tall. The base is lined with malachite." },
  { q: "How often is the FIFA World Cup held?", options: ["Every 2 years","Every 3 years","Every 4 years","Every 5 years"], answer: "Every 4 years", fact: "The World Cup is held every four years, in line with the Olympic cycle." },
  { q: "FIFA stands for what in French?", options: ["Fédération Internationale de Football Association","Fonds International de Football Amateur","Fédération Internatinale des Footballeurs Amateurs","Fonds Internatinaux pour le Football Amateur"], answer: "Fédération Internationale de Football Association", fact: "FIFA was founded in Paris in 1904 and is headquartered in Zurich, Switzerland." },
  { q: "In which year was FIFA founded?", options: ["1900","1904","1908","1912"], answer: "1904", fact: "FIFA was founded on 21 May 1904 in Paris, with just 7 European member associations." },
  { q: "Which country has qualified for every single FIFA World Cup?", options: ["Germany","Italy","Brazil","Argentina"], answer: "Brazil", fact: "Brazil is the only nation to have qualified for every FIFA World Cup, appearing in all 22 tournaments from 1930 to 2022." },
  { q: "Which is the only country other than the host to have failed to qualify for a World Cup after winning it?", options: ["Italy (2010)","France (2002)","Spain (2014)","Germany (2018)"], answer: "Italy (2010)", fact: "Defending champion Italy were eliminated in the group stage in 2010. But the question of 'failing to qualify' applies to France (2002) — who failed to score a single goal in the group stage as holders." },
  { q: "What year did the World Cup first include a third-place playoff match?", options: ["1930","1934","1938","1950"], answer: "1934", fact: "The third-place match was introduced at the 1934 World Cup in Italy, the second edition of the tournament." },
  { q: "An own goal in a World Cup group match gives which team credit?", options: ["The team that scored it","The opposing team","Neither team (no credit)","The team trailing on points"], answer: "The opposing team", fact: "In football statistics, an own goal is credited as a goal to the attacking team, but the scoring player is listed as 'OG'." },
  { q: "Which nationality of referee officiated the 2022 World Cup final?", options: ["French","English","Polish","Argentinian"], answer: "Polish", fact: "Szymon Marciniak of Poland refereed the 2022 final — he awarded no red cards and one VAR-checked penalty." },
  { q: "The ball used at the 2022 World Cup was called the:", options: ["Jabulani","Brazuca","Al Rihla","Telstar 18"], answer: "Al Rihla", fact: "Al Rihla (Arabic for 'the journey') was designed by Adidas and was said to be the fastest World Cup ball ever produced." },
  { q: "The ball used at the 2010 World Cup, notorious for its unpredictable movement, was called the:", options: ["Jabulani","Brazuca","Fevernova","Al Rihla"], answer: "Jabulani", fact: "The Jabulani's erratic flight path was criticised by goalkeepers across the tournament." },
  { q: "Adidas has provided the official match ball for every World Cup since which year?", options: ["1966","1970","1974","1978"], answer: "1970", fact: "Adidas has been the official ball manufacturer for every World Cup since Mexico 1970." },
  { q: "The mascot of the 2022 World Cup was called:", options: ["Zabivaka","Fuleco","Pique","La'eeb"], answer: "La'eeb", fact: "La'eeb was a ghost-like creature representing a 'super-skilled player'; the name means 'super skilled player' in Arabic." },
  { q: "The mascot of the 2018 Russia World Cup was called:", options: ["Pique","Naranjito","Zabivaka","Ciao"], answer: "Zabivaka", fact: "Zabivaka was a wolf in sporty gear; the name roughly translates to 'one who scores goals' in Russian." },
  { q: "Which player is the oldest to ever play in a World Cup final?", options: ["Dino Zoff","Roger Milla","Lothar Matthäus","Gianluigi Buffon"], answer: "Dino Zoff", fact: "Dino Zoff was 40 years old when he captained Italy in the 1982 World Cup final win over West Germany." },
  { q: "Roger Milla of Cameroon famously celebrated goals with a:", options: ["Backflip","Slide and dance at the corner flag","Somersault","Shirt-over-head"], answer: "Slide and dance at the corner flag", fact: "Milla's corner-flag dance became one of the most iconic World Cup celebrations of all time at Italia '90." },
  { q: "Roger Milla was how old when he scored at the 1994 World Cup, becoming the oldest scorer in tournament history?", options: ["38","40","42","44"], answer: "42", fact: "Milla came on as a substitute and scored against Russia at the 1994 World Cup, aged 42 years and 39 days." },
  { q: "Which team used a famous psychological tactic of drilling 'knock knock who's there' chants before the 1966 World Cup to disturb rival teams in their hotel?", options: ["England","West Germany","Brazil","USSR"], answer: "England", fact: "Alf Ramsey's England were renowned for strategic preparation but this particular detail is an urban myth — the real psychological detail is that England stayed in their 1966 base near the stadium throughout the tournament." },
  { q: "Who scored the first goal of the 2022 World Cup?", options: ["Enner Valencia","Mohammed Muntari","Kylian Mbappé","Cody Gakpo"], answer: "Enner Valencia", fact: "Valencia scored a penalty for Ecuador to put them 1-0 up against hosts Qatar in the tournament opener — though an earlier 'goal' was disallowed for offside." },
  { q: "England goalkeeper Peter Shilton made how many World Cup appearances?", options: ["13","15","17","19"], answer: "17", fact: "Shilton played 17 World Cup matches across three tournaments — one of the most by any goalkeeper." },
  { q: "Which country won the first World Cup on home soil since France in 1998?", options: ["Argentina (2022)","Germany (2014)","Spain (2010)","Brazil (2002)"], answer: "Argentina (2022)", fact: "Actually Brazil in 2014 was on home soil but they LOST. Spain in 2010 won in South Africa — not home. The last host to win was France 1998." },
  { q: "France became the second country to win a World Cup on their own soil in 1998 — who was the first?", options: ["England","Brazil","West Germany","Uruguay"], answer: "Uruguay", fact: "Uruguay won the first World Cup on home soil in 1930; England won in 1966 but the answer to the specific question about 'second' after Uruguay is West Germany (1974)." },
  { q: "Which team holds the record for the most consecutive World Cup wins (matches, not tournaments) in a single year?", options: ["Brazil 1970","Germany 2014","France 2018","Spain 2010"], answer: "Brazil 1970", fact: "Brazil were unbeaten across all 6 matches of the 1970 World Cup, winning them all and scoring 19 goals, conceding 7." },
  { q: "How many goals did Just Fontaine of France score in one World Cup tournament — a record never beaten?", options: ["10","11","12","13"], answer: "13", fact: "Fontaine scored 13 goals at the 1958 World Cup in Sweden — the most by any single player at a single tournament ever." },
  { q: "Which player scored the most goals in a single World Cup match?", options: ["Sándor Kocsis","Just Fontaine","Oleg Salenko","Ronaldo"], answer: "Oleg Salenko", fact: "Oleg Salenko scored 5 goals for Russia against Cameroon at the 1994 World Cup — the joint record for a single match alongside Sándor Kocsis's 4 in 1954 (Kocsis scored 4 in one game but never 5)." },
  { q: "Who holds the record for the most career World Cup goals before Miroslav Klose surpassed him?", options: ["Pelé","Ronaldo (Brazil)","Gerd Müller","Teófilo Cubillas"], answer: "Ronaldo (Brazil)", fact: "Brazilian Ronaldo R9 scored 15 World Cup goals in 1994, 1998, 2002 and 2006, holding the record until Klose broke it in 2014." },
 
  // ── MANAGERS & COACHES ────────────────────────────────────────────────────
  { q: "Which manager has won the World Cup as both a player and a manager?", options: ["Johan Cruyff","Franz Beckenbauer","Diego Maradona","Didier Deschamps"], answer: "Didier Deschamps", fact: "Deschamps captained France to the 1998 title and managed the 2018 champions. Franz Beckenbauer did the same (1974 player, 1990 manager)." },
  { q: "Franz Beckenbauer won the World Cup as player (1974) and manager (1990) for which country?", options: ["Austria","Switzerland","West Germany","East Germany"], answer: "West Germany", fact: "Beckenbauer is the only person to win the World Cup as both captain and manager of the same nation (West Germany/Germany)." },
  { q: "Which was the first manager to win the World Cup with two different countries?", options: ["No one has ever done this","Marcello Lippi","Vicente del Bosque","Sven-Göran Eriksson"], answer: "No one has ever done this", fact: "No manager has ever won the World Cup with two different nations — it remains one of football's unfulfilled achievements." },
  { q: "Who managed Brazil at both the 2014 and 2018 World Cups?", options: ["Carlos Alberto Parreira","Luiz Felipe Scolari","Tite","Dunga"], answer: "Tite", fact: "Tite managed Brazil from 2016 through both the 2018 (quarter-finals) and 2022 World Cups." },
  { q: "Which legendary manager led England to 1966 World Cup glory?", options: ["Don Revie","Ron Greenwood","Bobby Robson","Alf Ramsey"], answer: "Alf Ramsey", fact: "Sir Alf Ramsey's 'Wingless Wonders' system was revolutionary; he was knighted after the victory." },
 
  // ── EXTRA OBSCURE / DIFFICULT ─────────────────────────────────────────────
  { q: "What was the name of the famous English referee who 'invented' yellow and red cards?", options: ["Jack Taylor","Gordon Hill","Ken Aston","Jim Finney"], answer: "Ken Aston", fact: "Aston had the idea while driving; the yellow and red card system was introduced at the 1970 World Cup." },
  { q: "Which team was the first from Africa to reach a World Cup quarter-final?", options: ["Senegal","Ghana","Cameroon","Morocco"], answer: "Cameroon", fact: "Cameroon reached the quarter-finals of Italia 1990 — the first African side to reach that stage." },
  { q: "The first World Cup match to use video review (VAR) to award a penalty was in which match in 2018?", options: ["France vs Australia","Spain vs Portugal","Germany vs Mexico","Russia vs Saudi Arabia"], answer: "France vs Australia", fact: "VAR was used to award France a penalty against Australia, which Antoine Griezmann converted — the first VAR penalty in World Cup history." },
  { q: "Which country sent the team that received the first yellow card in World Cup history?", options: ["Brazil","Mexico","Soviet Union","England"], answer: "Soviet Union", fact: "Kakhi Asatiani of the Soviet Union received the first yellow card at the 1970 World Cup." },
  { q: "How many times has the World Cup final gone to a penalty shootout (as of 2022)?", options: ["1","2","3","4"], answer: "2", fact: "Only 1994 (Italy vs Brazil) and 2022 (Argentina vs France) have gone to a shootout. All others were decided in 90 minutes or extra time." },
  { q: "Which team scored the most goals at a single World Cup tournament?", options: ["Hungary 1954","France 1958","Brazil 1970","Germany 1954"], answer: "Hungary 1954", fact: "Hungary scored 27 goals in 5 matches at the 1954 World Cup (including a 10-1 win over El Salvador in 1982 for a single-game record)." },
  { q: "Who was the first player to score in consecutive World Cup finals?", options: ["Pelé","Kylian Mbappé","Zinedine Zidane","Vavá"], answer: "Vavá", fact: "Brazilian striker Vavá scored in both the 1958 and 1962 World Cup finals." },
  { q: "Kylian Mbappé scored in the 2018 and 2022 World Cup finals — true or false?", options: ["True","False"], answer: "True", fact: "Mbappé scored in the 2018 final (4th goal in 4-2 win) and scored a hat-trick in the 2022 final (France lost 3-3, 4-2 pens)." },
  { q: "The only brothers to play against each other in a World Cup final are:", options: ["Gary and Phil Neville","Bixente Lizarazu and a sibling","Raimund and Walter Kopa","No brothers have done this"], answer: "No brothers have done this", fact: "Brothers have played together (e.g. Ghana's Boateng brothers were on opposing sides in 2010, but not in a final) — no brothers have met in a World Cup final." },
  { q: "Which current world record transfer fee player scored at the 2022 World Cup?", options: ["Neymar","Kylian Mbappé","Erling Haaland","Paul Pogba"], answer: "Kylian Mbappé", fact: "Mbappé holds the record for the highest transfer fee ever paid (€180m+, Real Madrid 2024). He scored 8 goals at the 2022 World Cup." },
  { q: "How many own goals were scored at the 2022 World Cup — a tournament record?", options: ["3","5","7","9"], answer: "5", fact: "The 2022 World Cup produced 5 own goals, the most at any World Cup. They included one in the final by... neither team (the 2-2 extra-time moment was a Mbappé tap-in)." },
  { q: "Which player scored the first World Cup hat-trick?", options: ["Geoff Hurst","Sándor Kocsis","Bert Patenaude","Tom Finney"], answer: "Bert Patenaude", fact: "American Bert Patenaude scored the first World Cup hat-trick against Paraguay in 1930. FIFA confirmed the record in 2006 after reviewing the historical evidence." },
  { q: "Which country has the most players who have won the World Cup Golden Ball?", options: ["Brazil","Argentina","France","Germany"], answer: "Argentina", fact: "Argentina players have won the Golden Ball 4 times: Mario Kempes (1978), Diego Maradona (1986), Ronaldo (1994 — Brazilian), Lionel Messi (2014 & 2022)." },
  { q: "How many teams from Asia qualified for the 2022 World Cup?", options: ["4","5","6","7"], answer: "6", fact: "Australia (OFC/AFC), Japan, South Korea, Saudi Arabia, Iran and Qatar (as hosts) — 6 Asian-confederation teams participated." },
  { q: "Which team had the biggest squad age average at the 2022 World Cup?", options: ["Qatar","Iran","Tunisia","Mexico"], answer: "Iran", fact: "Iran had an average squad age of over 28 years, one of the oldest in the tournament." },
  { q: "Who presented the 2022 World Cup trophy to Lionel Messi?", options: ["FIFA President Gianni Infantino","Qatar's Emir Sheikh Tamim","King of Spain Felipe VI","FIFA Secretary General Fatma Samoura"], answer: "Qatar's Emir Sheikh Tamim", fact: "The Emir of Qatar, Sheikh Tamim bin Hamad Al Thani, draped a traditional bisht robe over Messi before he lifted the trophy." },
  { q: "What is a 'bisht' — the garment placed on Messi at the 2022 World Cup trophy ceremony?", options: ["A football shirt","A traditional Arab cloak worn on special occasions","A referee's jacket","A medal ribbon"], answer: "A traditional Arab cloak worn on special occasions", fact: "The bisht is a traditional Arabian cloak worn at weddings and other ceremonies; placing it on Messi was a mark of honour." },
 
];

if (typeof module !== "undefined") module.exports = TRIVIA_QUESTIONS;
