const SUBJECTS = [
  ["mathematics", "Mathematics", "Subject", "Numbers, structure, patterns, modelling, proof, statistics, and problem solving."],
  ["physics", "Physics", "Subject", "Motion, forces, energy, waves, electricity, quantum ideas, and the physical universe."],
  ["chemistry", "Chemistry", "Subject", "Matter, reactions, bonding, acids and bases, organic chemistry, and laboratory thinking."],
  ["biology", "Biology", "Subject", "Cells, genetics, evolution, ecosystems, body systems, and living processes."],
  ["modern-history", "Modern History", "Subject", "Political change, conflict, ideology, source analysis, and the making of the modern world."],
  ["ancient-history", "Ancient History", "Subject", "Civilisations, archaeology, ancient power, belief, culture, and evidence."],
  ["english", "English", "Subject", "Reading, writing, rhetoric, storytelling, argument, context, and textual analysis."],
  ["economics", "Economics", "Subject", "Markets, incentives, trade, inflation, policy, inequality, and decision-making under scarcity."],
  ["business-studies", "Business Studies", "Subject", "Marketing, operations, finance, human resources, entrepreneurship, and strategy."],
  ["legal-studies", "Legal Studies", "Subject", "Rights, law reform, courts, justice, crime, human rights, and legal systems."],
  ["engineering", "Engineering", "Subject", "Design, materials, systems, mechanics, problem solving, and applied innovation."],
  ["software-design", "Software Design", "Subject", "Algorithms, data, interfaces, programming, architecture, and building reliable systems."],
  ["religion", "Studies of Religion", "Subject", "Belief systems, ethics, rituals, sacred texts, identity, and religious influence."],
  ["geography", "Geography", "Subject", "Places, environments, population, climate, mapping, urban change, and human systems."],
  ["art", "Visual Arts", "Subject", "Practice, symbolism, composition, criticism, art history, and visual meaning."],
  ["music", "Music", "Subject", "Performance, composition, listening, theory, production, and cultural expression."],
  ["health", "Health and PDHPE", "Subject", "Wellbeing, movement, identity, safety, health systems, and performance."],
  ["computer-science", "Computer Science", "Subject", "Computation, networks, security, databases, AI, programming, and digital systems."],
  ["media-studies", "Media Studies", "Subject", "Platforms, audiences, representation, influence, production, and digital culture."],
  ["psychology", "Psychology", "Subject", "Mind, behaviour, memory, development, emotion, cognition, and social influence."]
].map(([id, name, category, summary]) => profile(id, name, category, "Academic field", summary, ["Core ideas", "Key people", "Important debates", "Study angles"]));

const PEOPLE = [
  ["aboflah", "AboFlah", "YouTuber", "Gaming, charity livestreams, Arabic-language creator culture", ["Arabic gaming content", "Large-scale charity campaigns", "Creator-led fundraising", "Youth audience"]],
  ["mrbeast", "MrBeast", "YouTuber", "Large-scale challenge videos, philanthropy, creator businesses", ["High-budget YouTube formats", "Philanthropy videos", "Creator entrepreneurship", "Viral retention strategy"]],
  ["pewdiepie", "PewDiePie", "YouTuber", "Gaming commentary, internet culture, long-running creator influence", ["Gaming commentary", "YouTube history", "Creator independence", "Meme culture"]],
  ["mark-rober", "Mark Rober", "YouTuber", "Engineering education, science builds, accessible STEM storytelling", ["Engineering experiments", "Science communication", "Educational entertainment", "Maker culture"]],
  ["dude-perfect", "Dude Perfect", "YouTuber", "Sports entertainment, trick shots, family-friendly challenge videos", ["Trick shots", "Sports comedy", "Group creator brand", "Family audience"]],
  ["ksi", "KSI", "YouTuber", "YouTube entertainment, boxing, music, Sidemen, creator business", ["Sidemen", "Boxing events", "Music career", "Creator economy"]],
  ["logan-paul", "Logan Paul", "YouTuber", "YouTube entertainment, boxing, podcasting, sports entertainment", ["Creator controversy", "Boxing", "Podcasting", "WWE and sports media"]],
  ["jake-paul", "Jake Paul", "YouTuber", "Creator boxing, social media fame, entertainment business", ["Creator boxing", "Promotion", "Social media strategy", "Public image"]],
  ["sidemen", "Sidemen", "YouTube Group", "British creator group known for challenges, football videos, and entertainment", ["Group chemistry", "Challenge formats", "UK YouTube", "Creator businesses"]],
  ["ishowspeed", "IShowSpeed", "Streamer", "High-energy livestreaming, football fandom, youth internet culture", ["Livestream personality", "Football culture", "Reaction content", "Audience intensity"]],
  ["kai-cenat", "Kai Cenat", "Streamer", "Livestream entertainment, creator collaborations, youth culture", ["Streaming records", "Collaborations", "Comedy", "Creator fandom"]],
  ["dream", "Dream", "YouTuber", "Minecraft videos, speedrunning culture, creator mystery and fandom", ["Minecraft", "Speedrunning", "Online fandom", "Creator identity"]],
  ["markiplier", "Markiplier", "YouTuber", "Gaming, horror playthroughs, charity streams, creator storytelling", ["Gaming commentary", "Horror games", "Charity work", "Narrative projects"]],
  ["jacksepticeye", "Jacksepticeye", "YouTuber", "Gaming commentary, Irish creator identity, charity livestreams", ["Let's Plays", "Creator longevity", "Charity events", "Community connection"]],
  ["dantdm", "DanTDM", "YouTuber", "Minecraft, family-friendly gaming, long-running creator career", ["Minecraft", "Family gaming", "Creator evolution", "YouTube longevity"]],
  ["preston", "Preston", "YouTuber", "Minecraft, challenge content, family-friendly gaming videos", ["Gaming challenges", "Minecraft", "Creator brand", "Younger audiences"]],
  ["ninja", "Ninja", "Streamer", "Fortnite streaming, esports celebrity, mainstream gaming attention", ["Fortnite", "Streaming platforms", "Esports fame", "Creator sponsorships"]],
  ["pokimane", "Pokimane", "Streamer", "Twitch streaming, gaming, online community, creator leadership", ["Twitch culture", "Community building", "Gaming content", "Creator business"]],
  ["valkyrae", "Valkyrae", "Streamer", "Gaming livestreams, creator leadership, YouTube gaming culture", ["Livestreaming", "Gaming collabs", "Creator ownership", "Community"]],
  ["lazarbeam", "LazarBeam", "YouTuber", "Australian gaming comedy, Fortnite, casual creator humour", ["Fortnite", "Australian YouTube", "Gaming comedy", "Casual entertainment"]],
  ["dhar-mann", "Dhar Mann", "Creator", "Moral-story videos, short-form lessons, scripted social content", ["Short moral stories", "Scripted internet drama", "Lesson-based content", "Mass audience"]],
  ["ryan-trahan", "Ryan Trahan", "YouTuber", "Challenge storytelling, travel concepts, creator fundraising", ["Narrative challenges", "Travel videos", "Fundraising", "Minimalist premises"]],
  ["yes-theory", "Yes Theory", "YouTube Group", "Adventure storytelling and the idea of seeking discomfort", ["Travel storytelling", "Self-development", "Adventure", "Community challenges"]],
  ["mkbhd", "Marques Brownlee", "YouTuber", "Consumer technology reviews, video production, product analysis", ["Tech reviews", "Smartphones", "Production quality", "Consumer trust"]],
  ["linus-tech-tips", "Linus Tech Tips", "YouTube Channel", "PC hardware, technology explainers, enthusiast tech media", ["Computer hardware", "Tech testing", "PC building", "Creator media company"]],
  ["mrwhosetheboss", "Mrwhosetheboss", "YouTuber", "Consumer tech videos, smartphone coverage, gadget storytelling", ["Smartphones", "Tech comparisons", "Gadgets", "Accessible tech"]],
  ["veritasium", "Veritasium", "YouTuber", "Science education, physics explanations, curiosity-led documentaries", ["Physics", "Science history", "Experiments", "Misconceptions"]],
  ["kurzgesagt", "Kurzgesagt", "YouTube Channel", "Animated science, philosophy, future thinking, big questions", ["Animation", "Science explainers", "Philosophy", "Future scenarios"]],
  ["smarter-every-day", "SmarterEveryDay", "YouTuber", "Engineering, physics, slow-motion experiments, curiosity videos", ["Engineering", "Physics", "Experiment design", "Learning through observation"]],
  ["nilered", "NileRed", "YouTuber", "Chemistry experiments and long-form laboratory storytelling", ["Chemistry", "Lab process", "Experiment videos", "Science curiosity"]],
  ["vsauce", "Vsauce", "YouTuber", "Philosophical science questions, internet education, curiosity essays", ["Big questions", "Science communication", "Philosophy", "Internet learning"]],
  ["matpat", "MatPat", "YouTuber", "Game, film, food, and style theory channels", ["Theory videos", "Analysis formats", "Gaming culture", "Creator networks"]],
  ["good-mythical-morning", "Good Mythical Morning", "YouTube Show", "Comedy, food experiments, daily entertainment format", ["Comedy duo", "Food formats", "Daily show", "Creator studio"]],
  ["beta-squad", "Beta Squad", "YouTube Group", "UK challenge videos, comedy formats, group entertainment", ["UK YouTube", "Group comedy", "Challenges", "Creator collaborations"]],
  ["niko-omilana", "Niko Omilana", "YouTuber", "Pranks, public stunts, UK creator culture, political satire", ["Public stunts", "Pranks", "UK internet culture", "Satire"]],
  ["chunkz", "Chunkz", "Creator", "Comedy, football entertainment, UK creator collaborations", ["Comedy", "Football videos", "Music and entertainment", "UK creators"]],
  ["airrack", "Airrack", "YouTuber", "Challenge videos, creator growth strategy, spectacle formats", ["Challenges", "Creator growth", "Collaboration", "Viral formats"]],
  ["emma-chamberlain", "Emma Chamberlain", "Creator", "Lifestyle videos, fashion, podcasting, creator authenticity", ["Lifestyle", "Fashion", "Podcasting", "Creator voice"]],
  ["khaby-lame", "Khaby Lame", "TikToker", "Silent comedy, reaction videos, global short-form fame", ["Physical comedy", "TikTok growth", "Universal humour", "Short-form video"]],
  ["charli-damelio", "Charli D'Amelio", "TikToker", "Dance videos, TikTok celebrity, mainstream creator fame", ["Dance trends", "TikTok celebrity", "Family brand", "Youth culture"]],
  ["addison-rae", "Addison Rae", "TikToker", "Dance content, acting, music, social media celebrity", ["TikTok fame", "Entertainment crossover", "Dance culture", "Influencer branding"]],
  ["bella-poarch", "Bella Poarch", "TikToker", "Viral lip-sync videos, music career, creator identity", ["TikTok virality", "Music", "Visual branding", "Short-form fandom"]],
  ["zach-king", "Zach King", "Creator", "Visual illusions, short-form editing, family-friendly magic videos", ["Editing illusions", "Short-form storytelling", "Visual tricks", "Creative production"]],
  ["alix-earle", "Alix Earle", "Creator", "Lifestyle, beauty, personality-led short-form content", ["Lifestyle influence", "Beauty content", "Audience intimacy", "Trendsetting"]],
  ["wisdom-kaye", "Wisdom Kaye", "Creator", "Fashion-focused short-form content and styling influence", ["Fashion", "Styling", "Visual identity", "Creator modelling"]],
  ["spencer-x", "Spencer X", "Creator", "Beatboxing, music performance, short-form audio creativity", ["Beatboxing", "Music content", "Short-form performance", "Creator collaborations"]],
  ["dixie-damelio", "Dixie D'Amelio", "Creator", "TikTok fame, music, family media presence", ["Music", "TikTok fame", "Family brand", "Entertainment crossover"]],
  ["loren-gray", "Loren Gray", "Creator", "Social media fame, music, early short-form creator culture", ["Music", "Influencer culture", "Short-form platforms", "Online identity"]],
  ["taylor-swift", "Taylor Swift", "Celebrity", "Songwriting, pop culture, tours, fandom, music industry influence", ["Songwriting", "Fandom", "Music business", "Cultural moments"]],
  ["beyonce", "Beyonce", "Celebrity", "Music, performance, visual albums, cultural influence", ["Performance", "Albums", "Visual storytelling", "Cultural influence"]],
  ["rihanna", "Rihanna", "Celebrity", "Music, fashion, beauty entrepreneurship, pop culture", ["Music", "Beauty business", "Fashion", "Celebrity brand"]],
  ["drake", "Drake", "Celebrity", "Hip-hop, pop rap, streaming-era music influence", ["Rap", "Streaming", "Pop culture", "Music charts"]],
  ["the-weeknd", "The Weeknd", "Celebrity", "R&B, pop, cinematic music identity, major tours", ["R&B", "Pop", "Visual eras", "Performance"]],
  ["ariana-grande", "Ariana Grande", "Celebrity", "Pop vocals, acting roots, celebrity fandom", ["Pop music", "Vocals", "Acting", "Fandom"]],
  ["billie-eilish", "Billie Eilish", "Celebrity", "Alternative pop, visual identity, youth culture, songwriting", ["Alternative pop", "Songwriting", "Visual style", "Youth culture"]],
  ["selena-gomez", "Selena Gomez", "Celebrity", "Acting, music, beauty business, public advocacy", ["Acting", "Music", "Beauty brand", "Mental health advocacy"]],
  ["zendaya", "Zendaya", "Celebrity", "Acting, fashion, youth culture, major film and TV roles", ["Acting", "Fashion", "Film", "Television"]],
  ["dwayne-johnson", "Dwayne Johnson", "Celebrity", "Wrestling, film, business, mainstream entertainment", ["Wrestling", "Movies", "Branding", "Motivation"]],
  ["cristiano-ronaldo", "Cristiano Ronaldo", "Athlete", "Football, elite performance, global sports celebrity", ["Football", "Fitness", "Records", "Global fandom"]],
  ["lionel-messi", "Lionel Messi", "Athlete", "Football, playmaking, World Cup legacy, global sports culture", ["Football", "World Cup", "Playmaking", "Legacy"]],
  ["lebron-james", "LeBron James", "Athlete", "Basketball, longevity, sports business, cultural influence", ["Basketball", "NBA", "Longevity", "Sports media"]],
  ["kim-kardashian", "Kim Kardashian", "Celebrity", "Reality television, fashion, beauty, media entrepreneurship", ["Reality TV", "Fashion", "Business", "Media influence"]],
  ["kylie-jenner", "Kylie Jenner", "Celebrity", "Beauty business, social media influence, reality television", ["Beauty brand", "Social media", "Fashion", "Family media"]],
  ["tom-holland", "Tom Holland", "Celebrity", "Acting, Spider-Man role, film celebrity", ["Acting", "Film", "Spider-Man", "Youth fandom"]],
  ["jenna-ortega", "Jenna Ortega", "Celebrity", "Acting, horror roles, youth pop culture", ["Acting", "Horror", "Television", "Fashion"]],
  ["margot-robbie", "Margot Robbie", "Celebrity", "Acting, film production, major Hollywood roles", ["Acting", "Film production", "Hollywood", "Character roles"]],
  ["ryan-reynolds", "Ryan Reynolds", "Celebrity", "Acting, comedy, marketing, business ventures", ["Acting", "Comedy", "Marketing", "Business"]],
  ["keanu-reeves", "Keanu Reeves", "Celebrity", "Film roles, action cinema, public image", ["Acting", "Action cinema", "Public image", "Film legacy"]],
  ["pedro-pascal", "Pedro Pascal", "Celebrity", "Television and film acting, genre roles, internet fandom", ["Acting", "Television", "Film", "Fandom"]],
  ["bad-bunny", "Bad Bunny", "Celebrity", "Latin music, fashion, performance, global pop culture", ["Latin music", "Fashion", "Performance", "Cultural influence"]],
  ["shakira", "Shakira", "Celebrity", "Latin pop, dance, global music influence", ["Music", "Dance", "Latin pop", "Global fame"]],
  ["sza", "SZA", "Celebrity", "R&B songwriting, vocals, emotional pop culture impact", ["R&B", "Songwriting", "Vocals", "Fandom"]],
  ["albert-einstein", "Albert Einstein", "Historical Figure", "Physics, relativity, scientific imagination, public intellectual life", ["Relativity", "Physics", "Science history", "Public ideas"]],
  ["nikola-tesla", "Nikola Tesla", "Historical Figure", "Electrical invention, AC power systems, inventor mythology", ["Electricity", "Invention", "Engineering history", "Myth and legacy"]],
  ["isaac-newton", "Isaac Newton", "Historical Figure", "Physics, calculus, gravity, scientific revolution", ["Gravity", "Calculus", "Mechanics", "Scientific method"]],
  ["marie-curie", "Marie Curie", "Historical Figure", "Radioactivity research, chemistry, physics, scientific perseverance", ["Radioactivity", "Chemistry", "Physics", "Women in science"]],
  ["leonardo-da-vinci", "Leonardo da Vinci", "Historical Figure", "Art, invention, anatomy, Renaissance curiosity", ["Art", "Engineering sketches", "Anatomy", "Renaissance"]],
  ["cleopatra", "Cleopatra", "Historical Figure", "Ancient Egypt, political power, Roman alliances, historical image", ["Egypt", "Politics", "Rome", "Historical memory"]],
  ["julius-caesar", "Julius Caesar", "Historical Figure", "Roman politics, military leadership, republic and empire", ["Rome", "Military strategy", "Power", "Political change"]],
  ["alexander-the-great", "Alexander the Great", "Historical Figure", "Conquest, empire, Hellenistic world, military ambition", ["Empire", "Military history", "Hellenistic culture", "Leadership"]],
  ["napoleon", "Napoleon Bonaparte", "Historical Figure", "French Revolution aftermath, empire, warfare, law", ["France", "Military strategy", "Law", "Empire"]],
  ["abraham-lincoln", "Abraham Lincoln", "Historical Figure", "US Civil War, presidency, emancipation, political leadership", ["Civil War", "Leadership", "Emancipation", "Democracy"]],
  ["martin-luther-king-jr", "Martin Luther King Jr.", "Historical Figure", "Civil rights, nonviolent protest, speeches, justice movements", ["Civil rights", "Nonviolence", "Public speaking", "Justice"]],
  ["nelson-mandela", "Nelson Mandela", "Historical Figure", "Anti-apartheid struggle, reconciliation, democratic leadership", ["Apartheid", "Leadership", "Reconciliation", "Human rights"]],
  ["mahatma-gandhi", "Mahatma Gandhi", "Historical Figure", "Indian independence, nonviolent resistance, political ethics", ["Independence", "Nonviolence", "Ethics", "Colonial history"]],
  ["william-shakespeare", "William Shakespeare", "Historical Figure", "Drama, poetry, language, enduring literary influence", ["Theatre", "Poetry", "Language", "Literary themes"]],
  ["charles-darwin", "Charles Darwin", "Historical Figure", "Evolution, natural selection, scientific controversy", ["Evolution", "Biology", "Natural selection", "Science and society"]],
  ["ada-lovelace", "Ada Lovelace", "Historical Figure", "Early computing ideas, mathematics, analytical engine", ["Computing history", "Mathematics", "Algorithms", "Innovation"]],
  ["alan-turing", "Alan Turing", "Historical Figure", "Computing, codebreaking, artificial intelligence foundations", ["Computing", "Codebreaking", "AI history", "Logic"]],
  ["rosa-parks", "Rosa Parks", "Historical Figure", "Civil rights, protest, Montgomery Bus Boycott", ["Civil rights", "Protest", "Courage", "Social change"]],
  ["winston-churchill", "Winston Churchill", "Historical Figure", "Wartime leadership, speeches, British politics", ["World War II", "Leadership", "Speeches", "Political legacy"]],
  ["harriet-tubman", "Harriet Tubman", "Historical Figure", "Abolition, Underground Railroad, courage and liberation", ["Abolition", "Freedom", "Leadership", "Resistance"]]
].map(([id, name, category, summary, tags]) => profile(id, name, category, "Public figure", summary, tags));

const PROFILES = [...PEOPLE, ...SUBJECTS];

if (typeof window !== "undefined") {
  window.PROFILES = PROFILES;
}

function profile(id, name, category, role, summary, tags) {
  return {
    id,
    name,
    category,
    role,
    summary,
    tags,
    overview: `${name} is included in this local TrendScope library because people often research ${category.toLowerCase()} topics through identity, influence, audience, legacy, and the way public attention forms around them.`,
    why: `${name} can be studied by looking at the public story, the audience or historical context, the main achievements or controversies, and how media turns a person or subject into a wider cultural reference point.`,
    angles: [
      "What made this person, creator, celebrity, figure, or subject widely recognised?",
      "Which audience, community, era, or field gives the topic its meaning?",
      "What should a student or reader verify from reliable sources before making strong claims?",
      "How does the topic connect to culture, education, business, history, or online attention?"
    ]
  };
}
