tunnel: loma
credentials-file: C:\Users\youse\.cloudflared\e8008f38-fb90-4749-873a-f8a90e758c49.json

ingress:
  - hostname: api.envizion.work
    service: http://localhost:3000
  - service: http_status:404
